-- Verification plan for Supabase Auth login deletion.
-- Run against an isolated Supabase test database with fixture users/roles.
-- The protected HTTP route covers Auth Admin API success/failure; these SQL checks focus on database invariants.

begin;

-- Required fixtures/placeholders for an executable run:
--   :developer_auth_jwt              JWT for an active DEVELOPER
--   :chief_auth_jwt                  JWT for an active CHIEF
--   :admin_auth_jwt                  JWT for an active ADMIN
--   :prosecutor_auth_jwt             JWT for an active PROSECUTOR
--   :service_role_jwt                service-role JWT
--   :developer_app_user_id           active DEVELOPER public.users.id
--   :chief_app_user_id               active CHIEF public.users.id
--   :ordinary_app_user_id            active non-DEVELOPER public.users.id with auth_user_id
--   :ordinary_auth_user_id           auth UUID originally linked to :ordinary_app_user_id
--   :different_auth_user_id          UUID not equal to :ordinary_auth_user_id

-- Existing coverage:
-- 1. DEVELOPER can prepare/finalize an ordinary user's Auth login deletion.
-- 2. CHIEF can prepare/finalize an ordinary user's Auth login deletion.
-- 3. CHIEF cannot prepare deletion of a DEVELOPER login.
-- 4. ADMIN cannot prepare deletion.
-- 5. PROSECUTOR cannot prepare deletion.
-- 6. Self-deletion is rejected by prepare_auth_account_deletion.
-- 7. The final active DEVELOPER login is rejected.
-- 8. A target whose auth_user_id is NULL raises a controlled conflict in prepare_auth_account_deletion.
-- 9. record_auth_account_deletion_failure preserves public.users.auth_user_id.
-- 10. finalize_auth_account_deletion leaves public.users in place.
-- 11. finalize_auth_account_deletion sets is_active=false.
-- 12. finalize_auth_account_deletion sets auth_user_id=NULL.
-- 13. finalize_auth_account_deletion leaves public.user_roles intact.
-- 14. Historical rows that reference public.users(id) remain valid because the user row is preserved.
-- 15. finalize_auth_account_deletion and record_auth_account_deletion_failure insert audit_logs rows.
-- 16. Unauthenticated API calls should return 401 (covered by route handler/manual HTTP test).
-- 17. Unauthorized API calls should return 403 (database 42501 mapped by route handler).

-- Additional security checks added for service-role-only finalize/failure RPCs:
-- 18. Authenticated users cannot call finalize_auth_account_deletion(bigint, uuid, bigint) directly.
--     Expected: permission denied for authenticated role.
--     Example:
--       set local role authenticated;
--       select public.finalize_auth_account_deletion(:ordinary_app_user_id, :ordinary_auth_user_id, :developer_app_user_id);
--
-- 19. Authenticated users cannot call record_auth_account_deletion_failure(bigint, uuid, text, bigint) directly.
--     Expected: permission denied for authenticated role.
--     Example:
--       set local role authenticated;
--       select public.record_auth_account_deletion_failure(:ordinary_app_user_id, :ordinary_auth_user_id, 'simulated failure', :developer_app_user_id);
--
-- 20. service_role can call finalize_auth_account_deletion and record_auth_account_deletion_failure.
--     Expected: both calls succeed when p_actor_user_id is an active DEVELOPER or CHIEF.
--     Example:
--       set local role service_role;
--       select public.record_auth_account_deletion_failure(:ordinary_app_user_id, :ordinary_auth_user_id, 'simulated failure', :developer_app_user_id);
--
-- 21. finalize_auth_account_deletion accepts auth_user_id already NULL from ON DELETE SET NULL.
--     Setup:
--       update public.users set auth_user_id = null, is_active = true where id = :ordinary_app_user_id;
--       select public.finalize_auth_account_deletion(:ordinary_app_user_id, :ordinary_auth_user_id, :developer_app_user_id);
--     Expected: public.users row remains, auth_user_id is NULL, is_active is false.
--
-- 22. finalize_auth_account_deletion rejects a different non-null UUID.
--     Setup:
--       update public.users set auth_user_id = :different_auth_user_id, is_active = true where id = :ordinary_app_user_id;
--       select public.finalize_auth_account_deletion(:ordinary_app_user_id, :ordinary_auth_user_id, :developer_app_user_id);
--     Expected: controlled conflict exception; auth_user_id remains :different_auth_user_id.
--
-- 23. Repeated finalize does not create duplicate success audit entries.
--     Setup:
--       select public.finalize_auth_account_deletion(:ordinary_app_user_id, :ordinary_auth_user_id, :developer_app_user_id);
--       select public.finalize_auth_account_deletion(:ordinary_app_user_id, :ordinary_auth_user_id, :developer_app_user_id);
--     Expected:
--       select count(*) = 1
--       from public.audit_logs
--       where entity_name = 'users'
--         and entity_id = :ordinary_app_user_id
--         and action = 'AUTH_LOGIN_ACCOUNT_DELETED'
--         and metadata->>'auth_user_id' = :ordinary_auth_user_id::text;
--
-- 24. public.users remains preserved and inactive after successful finalize.
--     Expected:
--       select exists (
--         select 1
--         from public.users u
--         where u.id = :ordinary_app_user_id
--           and u.auth_user_id is null
--           and u.is_active is false
--       );

-- Example invariant query after a successful finalize call:
-- select u.id, u.auth_user_id, u.is_active, ur.role_id
-- from public.users u
-- left join public.user_roles ur on ur.user_id = u.id
-- where u.id = :target_application_user_id;
-- Expected: one public.users row exists, auth_user_id is null, is_active is false, role_id is unchanged.

-- Example audit query:
-- select action, entity_name, entity_id, summary
-- from public.audit_logs
-- where entity_name = 'users'
--   and entity_id = :target_application_user_id
--   and action in ('AUTH_LOGIN_ACCOUNT_DELETED', 'AUTH_LOGIN_ACCOUNT_DELETE_FAILED')
-- order by created_at desc;

rollback;
