export type CasesReportRow = {
  docketNumber: string;
  complainant: string;
  respondent: string;
  violation: string;
  assignedProsecutor: string;
  currentStatus: string;
  dateApproved: string;
  dateReceived: string;
};

export type CasesReportFilters = {
  searchTerm: string;
  searchColumns: string[];
  docketTypes: string[];
  docketYears: string[];
  docketMonths: string[];
  activeColumnFilters: Array<{ column: string; values: string[] }>;
  sortOrder: string;
};

export type GenerateCasesReportOptions = {
  rows: CasesReportRow[];
  filters: CasesReportFilters;
  generatedBy: string;
  generatedAt?: Date;
};

type JsPdfWithAutoTable = import('jspdf').jsPDF & {
  lastAutoTable?: { finalY?: number };
};

function printableValue(value: string | string[]) {
  if (Array.isArray(value)) {
    return value.length > 0 ? value.join(', ') : 'None';
  }

  return value.trim() || 'None';
}

function formatGeneratedDateTime(date: Date) {
  return new Intl.DateTimeFormat(undefined, {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

function buildFilterLines(filters: CasesReportFilters) {
  return [
    ['Docket types', printableValue(filters.docketTypes)],
    ['Docket years', printableValue(filters.docketYears)],
    ['Docket months', filters.docketMonths.length > 0 ? filters.docketMonths.join('\n') : 'None'],
  ];
}

export async function generateCasesReportPdf({
  rows,
  filters,
  generatedBy,
  generatedAt = new Date(),
}: GenerateCasesReportOptions): Promise<Blob> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = autoTableModule.default;
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' }) as JsPdfWithAutoTable;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 28;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('REPUBLIC OF THE PHILIPPINES', pageWidth / 2, 30, { align: 'center' });
  doc.setFontSize(12);
  doc.text('OFFICE OF THE CITY PROSECUTOR', pageWidth / 2, 46, { align: 'center' });
  doc.setFontSize(10);
  doc.text('GENERAL TRIAS CITY', pageWidth / 2, 62, { align: 'center' });
  doc.setFontSize(13);
  doc.text('CASE LIST REPORT', pageWidth / 2, 92, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Generated date/time: ${formatGeneratedDateTime(generatedAt)}`, margin, 120);
  doc.text(`Generated by: ${generatedBy || 'Authenticated user'}`, margin, 132);
  doc.text(`Total exported cases: ${rows.length.toLocaleString()}`, margin, 144);

  autoTable(doc, {
    startY: 160,
    head: [['Applied Filters', 'Value']],
    body: buildFilterLines(filters),
    theme: 'grid',
    styles: { fontSize: 7, cellPadding: 3, overflow: 'linebreak', valign: 'top' },
    headStyles: { fillColor: [45, 55, 72], fontSize: 7 },
    columnStyles: { 0: { cellWidth: 105, fontStyle: 'bold' }, 1: { cellWidth: pageWidth - margin * 2 - 105 } },
    margin: { left: margin, right: margin },
  });

  autoTable(doc, {
    startY: (doc.lastAutoTable?.finalY ?? 160) + 12,
    head: [[
      'Docket Number',
      'Complainant',
      'Respondent',
      'Violation',
      'Assigned Prosecutor',
      'Current Status',
      'Date Approved',
      'Date Received',
    ]],
    body: rows.map((row) => [
      row.docketNumber,
      row.complainant,
      row.respondent,
      row.violation,
      row.assignedProsecutor,
      row.currentStatus,
      row.dateApproved,
      row.dateReceived,
    ]),
    theme: 'grid',
    showHead: 'everyPage',
    margin: { left: margin, right: margin, bottom: 34 },
    styles: { fontSize: 6.5, cellPadding: 3, overflow: 'linebreak', valign: 'top', lineWidth: 0.25 },
    headStyles: { fillColor: [31, 41, 55], fontSize: 6.5, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 78 },
      1: { cellWidth: 142 },
      2: { cellWidth: 142 },
      3: { cellWidth: 150 },
      4: { cellWidth: 96 },
      5: { cellWidth: 70 },
      6: { cellWidth: 58 },
      7: { cellWidth: 58 },
    },
    pageBreak: 'auto',
    rowPageBreak: 'auto',
  });

  const totalPages = doc.getNumberOfPages();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.text('Case List Report', margin, pageHeight - 14);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, pageHeight - 14, { align: 'right' });
  }

  return doc.output('blob');
}
