export type CaseDetailsReport = {
  docketNumber: string;
  generatedBy: string;
  generatedAt: Date;
  overview: {
    violationSummary: string | null;
    classification: string | null;
    dateReceived: string | null;
    assignedProsecutor: string | null;
    currentStatus: string | null;
    statusDate: string | null;
    currentStage: string | null;
    placeOfCommission: string | null;
    summaryProcedure: boolean | null;
    statusApprovedDate: string | null;
    statusRemarks: string | null;
    stageRemarks: string | null;
    summary: string | null;
    summaryRemarks: string | null;
  };
  violations: string[];
  parties: Array<{
    role: string;
    participants: Array<{
      name: string;
      aliases: string[];
      birthdateAndSex: string | null;
      ageAtCase: string | number | null;
      flags: string[];
      addresses: string[];
      contacts: string[];
      remarks: string | null;
      organizationDetails: string | null;
    }>;
  }>;
  timeline: Array<{
    date: string | null;
    category: string;
    title: string;
    details: string[];
  }>;
  notes: Array<{
    date: string | null;
    text: string;
    isPrivate: boolean;
  }>;
  attachments: Array<{
    fileName: string;
    fileSize: string;
    status: string;
    webViewLink: string | null;
  }>;
  unavailableSections: string[];
};

export type CaseDetailsReportOptions = {
  includeTimeline: boolean;
  includeAttachmentIndex: boolean;
  includePrivateNotes: boolean;
};

type JsPdfWithAutoTable = import('jspdf').jsPDF & {
  lastAutoTable?: { finalY?: number };
};

function clean(value: string | number | boolean | null | undefined) {
  if (value === null || value === undefined) return null;
  const text = String(value).trim();
  return text && text !== '—' ? text : null;
}

function formatGeneratedDateTime(date: Date) {
  return new Intl.DateTimeFormat(undefined, {
    year: 'numeric', month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit',
  }).format(date);
}

function addSectionTitle(doc: JsPdfWithAutoTable, title: string, y: number, margin: number) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y > pageHeight - 72) {
    doc.addPage();
    y = margin;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(title, margin, y);
  return y + 8;
}

function currentY(doc: JsPdfWithAutoTable, fallback: number) {
  return (doc.lastAutoTable?.finalY ?? fallback) + 14;
}

export async function generateCaseDetailsReportPdf(
  report: CaseDetailsReport,
  options: CaseDetailsReportOptions,
): Promise<Blob> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = autoTableModule.default;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' }) as JsPdfWithAutoTable;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const usableWidth = pageWidth - margin * 2;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('REPUBLIC OF THE PHILIPPINES', pageWidth / 2, 42, { align: 'center' });
  doc.setFontSize(12);
  doc.text('OFFICE OF THE CITY PROSECUTOR', pageWidth / 2, 59, { align: 'center' });
  doc.setFontSize(10);
  doc.text('GENERAL TRIAS CITY', pageWidth / 2, 76, { align: 'center' });
  doc.setFontSize(14);
  doc.text('CASE DETAILS REPORT', pageWidth / 2, 110, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Docket Number: ${report.docketNumber}`, margin, 138);
  doc.text(`Generated: ${formatGeneratedDateTime(report.generatedAt)}`, margin, 152);
  doc.text(`Generated by: ${report.generatedBy || 'Authenticated user'}`, margin, 166);

  let y = 190;
  if (report.unavailableSections.length > 0) {
    autoTable(doc, {
      startY: y,
      body: [[`Some sections are unavailable and were not included: ${report.unavailableSections.join('; ')}`]],
      theme: 'plain',
      styles: { fontSize: 8, cellPadding: 5, textColor: [120, 53, 15], fillColor: [255, 247, 237] },
      margin: { left: margin, right: margin, bottom: 44 },
    });
    y = currentY(doc, y);
  }

  y = addSectionTitle(doc, 'A. CASE OVERVIEW', y, margin);
  const overviewRows = [
    ['Docket Number', report.docketNumber],
    ['Violation summary', report.overview.violationSummary],
    ['Classification', report.overview.classification],
    ['Date Received', report.overview.dateReceived],
    ['Assigned Prosecutor', report.overview.assignedProsecutor],
    ['Current Status', report.overview.currentStatus],
    ['Status Date', report.overview.statusDate],
    ['Current Stage', report.overview.currentStage],
    ['Place of Commission', report.overview.placeOfCommission],
    ['Summary Procedure', report.overview.summaryProcedure === null ? null : report.overview.summaryProcedure ? 'Yes' : 'No'],
    ['Status Approved Date', report.overview.statusApprovedDate],
    ['Status Remarks', report.overview.statusRemarks],
    ['Stage Remarks', report.overview.stageRemarks],
    ['Summary', report.overview.summary],
    ['Summary Remarks', report.overview.summaryRemarks],
  ].filter(([, value]) => clean(value as string | null));
  autoTable(doc, {
    startY: y,
    body: overviewRows.length ? overviewRows : [['Case overview', 'No available overview values.']],
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
    columnStyles: { 0: { cellWidth: 135, fontStyle: 'bold' }, 1: { cellWidth: usableWidth - 135 } },
    margin: { left: margin, right: margin, bottom: 44 },
    rowPageBreak: 'auto',
  });

  y = addSectionTitle(doc, 'B. VIOLATIONS', currentY(doc, y), margin);
  autoTable(doc, {
    startY: y,
    body: report.violations.length ? report.violations.map((violation, index) => [`${index + 1}.`, violation]) : [['', 'No violations recorded.']],
    theme: 'plain',
    styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak', valign: 'top' },
    columnStyles: { 0: { cellWidth: 22 }, 1: { cellWidth: usableWidth - 22 } },
    margin: { left: margin, right: margin, bottom: 44 },
  });

  y = addSectionTitle(doc, 'C. PARTIES', currentY(doc, y), margin);
  const partyRows = report.parties.flatMap((group) => [
    [{ content: group.role, colSpan: 2, styles: { fontStyle: 'bold', fillColor: [243, 244, 246] } }],
    ...group.participants.map((participant) => {
      const details = [
        participant.aliases.length ? `Aliases: ${participant.aliases.join('\n')}` : null,
        participant.birthdateAndSex,
        clean(participant.ageAtCase) ? `Age at case: ${participant.ageAtCase}` : null,
        participant.flags.length ? `Flags: ${participant.flags.join(', ')}` : null,
        participant.addresses.length ? `Addresses:\n${participant.addresses.join('\n')}` : null,
        participant.contacts.length ? `Contacts:\n${participant.contacts.join('\n')}` : null,
        participant.remarks ? `Remarks: ${participant.remarks}` : null,
        participant.organizationDetails ? `Organization details: ${participant.organizationDetails}` : null,
      ].filter(Boolean).join('\n');
      return [participant.name, details || '—'];
    }),
  ]);
  autoTable(doc, {
    startY: y,
    head: [['Name', 'Details']],
    body: partyRows.length ? partyRows : [['Parties', 'No parties recorded.']],
    theme: 'grid', showHead: 'everyPage',
    styles: { fontSize: 7.5, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
    headStyles: { fillColor: [31, 41, 55], fontSize: 7.5 },
    columnStyles: { 0: { cellWidth: 150, fontStyle: 'bold' }, 1: { cellWidth: usableWidth - 150 } },
    margin: { left: margin, right: margin, bottom: 44 },
    rowPageBreak: 'auto',
  });

  if (options.includeTimeline) {
    y = addSectionTitle(doc, 'D. CASE TIMELINE', currentY(doc, y), margin);
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Category', 'Title / Details']],
      body: report.timeline.length ? report.timeline.map((item) => [item.date ?? '—', item.category, [item.title, ...item.details].filter(Boolean).join('\n')]) : [['—', 'Timeline', 'No timeline records available.']],
      theme: 'grid', showHead: 'everyPage',
      styles: { fontSize: 7.2, cellPadding: 3, overflow: 'linebreak', valign: 'top' },
      headStyles: { fillColor: [31, 41, 55], fontSize: 7.2 },
      columnStyles: { 0: { cellWidth: 75 }, 1: { cellWidth: 82 }, 2: { cellWidth: usableWidth - 157 } },
      margin: { left: margin, right: margin, bottom: 44 },
      rowPageBreak: 'auto',
    });
  }

  y = addSectionTitle(doc, 'E. CASE NOTES', currentY(doc, y), margin);
  const noteRows = report.notes
    .filter((note) => options.includePrivateNotes || !note.isPrivate)
    .map((note) => [note.date ?? '—', note.isPrivate ? 'PRIVATE' : '', note.text]);
  autoTable(doc, {
    startY: y,
    head: [['Date', 'Privacy', 'Note']],
    body: noteRows.length ? noteRows : [['—', '', 'No case notes included.']],
    theme: 'grid', showHead: 'everyPage',
    styles: { fontSize: 7.5, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
    headStyles: { fillColor: [31, 41, 55], fontSize: 7.5 },
    columnStyles: { 0: { cellWidth: 75 }, 1: { cellWidth: 58, fontStyle: 'bold' }, 2: { cellWidth: usableWidth - 133 } },
    margin: { left: margin, right: margin, bottom: 44 },
    rowPageBreak: 'auto',
  });

  if (options.includeAttachmentIndex) {
    y = addSectionTitle(doc, 'F. ATTACHMENT INDEX', currentY(doc, y), margin);
    autoTable(doc, {
      startY: y,
      head: [['File Name', 'File Size', 'Status']],
      body: report.attachments.length ? report.attachments.map((attachment) => [attachment.fileName, attachment.fileSize, attachment.status]) : [['No attachments indexed.', '—', '—']],
      theme: 'grid', showHead: 'everyPage',
      styles: { fontSize: 7.5, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
      headStyles: { fillColor: [31, 41, 55], fontSize: 7.5 },
      columnStyles: { 0: { cellWidth: usableWidth - 150 }, 1: { cellWidth: 70 }, 2: { cellWidth: 80 } },
      margin: { left: margin, right: margin, bottom: 44 },
      rowPageBreak: 'auto',
    });
  }

  const totalPages = doc.getNumberOfPages();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.text(`Case Details Report — ${report.docketNumber}`, margin, pageHeight - 18);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, pageHeight - 18, { align: 'right' });
  }

  return doc.output('blob');
}
