CREATE TABLE IF NOT EXISTS public.case_court_filing_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  court_filing_id bigint NOT NULL REFERENCES public.case_court_filings(id) ON DELETE CASCADE,
  case_resolution_approval_action_id bigint NOT NULL REFERENCES public.case_resolution_approval_actions(id),
  charge_filed text NOT NULL,
  display_order integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by_user_id bigint REFERENCES public.users(id),
  UNIQUE (court_filing_id, case_resolution_approval_action_id)
);
CREATE INDEX IF NOT EXISTS idx_court_filing_action_link ON public.case_court_filing_actions(case_resolution_approval_action_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.case_court_filing_actions TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

CREATE OR REPLACE FUNCTION public.record_court_filing_events_batch(
  p_case_id bigint, p_filings jsonb, p_court_id bigint DEFAULT NULL, p_court_name text DEFAULT NULL,
  p_court_branch text DEFAULT NULL, p_date_filed date DEFAULT NULL, p_time_filed time without time zone DEFAULT NULL,
  p_information_count integer DEFAULT NULL, p_criminal_case_numbers jsonb DEFAULT '[]'::jsonb,
  p_remarks text DEFAULT NULL, p_user_id bigint DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  filing jsonb; v_event_id bigint; v_court_filing_id bigint; number_text text; number_order integer := 0;
  filing_order integer := 0; normalized_numbers jsonb; first_action_id bigint; first_charge text; charge_summary text;
  final_status_code text; final_stage_code text; final_status_id bigint; final_stage_id bigint;
BEGIN
  IF jsonb_typeof(COALESCE(p_filings,'[]'::jsonb)) <> 'array' OR jsonb_array_length(COALESCE(p_filings,'[]'::jsonb)) = 0 THEN RAISE EXCEPTION 'At least one Court Filing charge is required'; END IF;
  IF jsonb_typeof(COALESCE(p_criminal_case_numbers,'[]'::jsonb)) <> 'array' THEN RAISE EXCEPTION 'Criminal Case Numbers must be an array'; END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_filings) item(value) WHERE NULLIF(btrim(item.value->>'charge_filed'),'') IS NULL) THEN RAISE EXCEPTION 'Every selected filing decision requires a Charge Filed value'; END IF;
  IF (SELECT count(*) FROM jsonb_array_elements(p_filings)) <> (SELECT count(DISTINCT (item.value->>'case_resolution_approval_action_id')) FROM jsonb_array_elements(p_filings) item(value)) THEN RAISE EXCEPTION 'Duplicate approved filing decisions are not allowed'; END IF;

  FOR filing IN SELECT value FROM jsonb_array_elements(p_filings) LOOP
    IF NULLIF(filing->>'case_resolution_approval_action_id','') IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.case_resolution_approval_actions aa JOIN public.case_resolution_approvals a ON a.id=aa.approval_id AND a.is_voided=false LEFT JOIN public.case_resolutions cr ON cr.id=a.case_resolution_id
      WHERE aa.id=(filing->>'case_resolution_approval_action_id')::bigint AND aa.case_id=p_case_id AND aa.decision_code='FOR_FILING' AND (a.case_resolution_id IS NULL OR cr.is_voided=false)
    ) THEN RAISE EXCEPTION 'No active approved FOR_FILING decision was found for this case'; END IF;
    IF NULLIF(filing->>'case_resolution_approval_action_id','') IS NOT NULL AND (
      EXISTS (SELECT 1 FROM public.case_court_filings cf WHERE cf.case_resolution_approval_action_id=(filing->>'case_resolution_approval_action_id')::bigint AND cf.is_voided=false)
      OR EXISTS (SELECT 1 FROM public.case_court_filing_actions cfa JOIN public.case_court_filings linked_cf ON linked_cf.id=cfa.court_filing_id AND linked_cf.is_voided=false WHERE cfa.case_resolution_approval_action_id=(filing->>'case_resolution_approval_action_id')::bigint)
    ) THEN RAISE EXCEPTION 'This approved filing decision already has an active Court Filing'; END IF;
  END LOOP;

  SELECT NULLIF(item.value->>'case_resolution_approval_action_id','')::bigint, btrim(item.value->>'charge_filed') INTO first_action_id,first_charge FROM jsonb_array_elements(p_filings) item(value) LIMIT 1;
  SELECT string_agg(btrim(item.value->>'charge_filed'), '; ' ORDER BY item.ordinality) INTO charge_summary FROM jsonb_array_elements(p_filings) WITH ORDINALITY item(value,ordinality);
  v_event_id := public.record_court_filing_event(p_case_id,first_action_id,p_court_id,p_court_name,p_court_branch,first_charge,p_date_filed,p_time_filed,p_information_count,NULL,p_remarks,p_user_id);
  SELECT id INTO v_court_filing_id FROM public.case_court_filings WHERE case_event_id=v_event_id AND is_voided=false;

  FOR filing IN SELECT value FROM jsonb_array_elements(p_filings) LOOP
    filing_order := filing_order + 1;
    IF NULLIF(filing->>'case_resolution_approval_action_id','') IS NOT NULL THEN
      INSERT INTO public.case_court_filing_actions(case_id,court_filing_id,case_resolution_approval_action_id,charge_filed,display_order,created_by_user_id)
      VALUES(p_case_id,v_court_filing_id,(filing->>'case_resolution_approval_action_id')::bigint,btrim(filing->>'charge_filed'),filing_order,p_user_id);
    END IF;
  END LOOP;

  SELECT COALESCE(jsonb_agg(value ORDER BY first_ordinality),'[]'::jsonb) INTO normalized_numbers FROM (SELECT DISTINCT ON(lower(btrim(value))) btrim(value) value,ordinality first_ordinality FROM jsonb_array_elements_text(COALESCE(p_criminal_case_numbers,'[]'::jsonb)) WITH ORDINALITY n(value,ordinality) WHERE btrim(value)<>'' ORDER BY lower(btrim(value)),ordinality) numbers;
  FOR number_text IN SELECT value FROM jsonb_array_elements_text(normalized_numbers) LOOP number_order:=number_order+1; INSERT INTO public.case_court_filing_criminal_cases(case_id,court_filing_id,criminal_case_no,sort_order,created_by_user_id,updated_by_user_id) VALUES(p_case_id,v_court_filing_id,number_text,number_order,p_user_id,p_user_id); END LOOP;

  UPDATE public.case_court_filings SET charge_filed=charge_summary,criminal_case_no=normalized_numbers->>0,updated_at=now(),updated_by_user_id=p_user_id WHERE id=v_court_filing_id;
  SELECT case_status_code,case_stage_code INTO final_status_code,final_stage_code FROM public.compute_current_case_state(p_case_id);
  SELECT id INTO final_status_id FROM public.case_statuses WHERE code=final_status_code AND is_active=true;
  SELECT id INTO final_stage_id FROM public.case_stages WHERE code=final_stage_code AND is_active=true;
  UPDATE public.case_private_details SET current_status_id=final_status_id,current_case_status_id=final_status_id,current_case_stage_id=final_stage_id,updated_at=now() WHERE case_id=p_case_id;
  UPDATE public.case_status_history SET to_status_id=final_status_id WHERE case_event_id=v_event_id;
  UPDATE public.case_stage_history SET to_stage_id=final_stage_id WHERE case_event_id=v_event_id;
  INSERT INTO public.case_status_history(case_id,from_status_id,to_status_id,changed_by_user_id,changed_at,status_date,remarks,case_event_id)
  SELECT p_case_id,NULLIF(ce.details_jsonb->>'previous_case_status_id','')::bigint,final_status_id,p_user_id,now(),p_date_filed,p_remarks,v_event_id FROM public.case_events ce WHERE ce.id=v_event_id AND NOT EXISTS(SELECT 1 FROM public.case_status_history h WHERE h.case_event_id=v_event_id) AND NULLIF(ce.details_jsonb->>'previous_case_status_id','')::bigint IS DISTINCT FROM final_status_id;
  INSERT INTO public.case_stage_history(case_id,from_stage_id,to_stage_id,changed_by_user_id,changed_at,stage_date,remarks,case_event_id)
  SELECT p_case_id,NULLIF(ce.details_jsonb->>'previous_case_stage_id','')::bigint,final_stage_id,p_user_id,now(),p_date_filed,p_remarks,v_event_id FROM public.case_events ce WHERE ce.id=v_event_id AND NOT EXISTS(SELECT 1 FROM public.case_stage_history h WHERE h.case_event_id=v_event_id) AND NULLIF(ce.details_jsonb->>'previous_case_stage_id','')::bigint IS DISTINCT FROM final_stage_id;
  UPDATE public.case_events SET status_id=final_status_id,case_status_id=final_status_id,case_stage_id=final_stage_id,details_jsonb=COALESCE(details_jsonb,'{}'::jsonb)||jsonb_build_object('charge_filed',charge_summary,'filing_actions',p_filings,'criminal_case_numbers',normalized_numbers,'case_status_code',final_status_code,'case_stage_code',final_stage_code),updated_at=now(),updated_by_user_id=p_user_id WHERE id=v_event_id;
  INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,new_data,case_id,summary,metadata) VALUES(p_user_id,'case_court_filings',v_court_filing_id,'COURT_FILING_ACTIONS_RECORDED',p_filings,p_case_id,'Multiple approved filing decisions recorded under one Court Filing.',jsonb_build_object('case_event_id',v_event_id,'approval_action_count',jsonb_array_length(p_filings)));
  RETURN v_event_id;
END $$;

GRANT EXECUTE ON FUNCTION public.record_court_filing_events_batch(bigint,jsonb,bigint,text,text,date,time without time zone,integer,jsonb,text,bigint) TO authenticated;
