INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
VALUES ('CASE_RESOLVED', 'Case Resolved', 'CASE', 'Manual timeline event for resolving a case.', 120, true, true)
ON CONFLICT (code) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
VALUES ('RESOLVED', 'Resolved', 80, true, true, true)
ON CONFLICT (code) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  is_final = true,
  is_milestone = true,
  is_active = true,
  updated_at = now();

CREATE TABLE IF NOT EXISTS public.case_resolutions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  case_event_id bigint UNIQUE REFERENCES public.case_events(id),
  recommendation_code text NOT NULL,
  date_resolved date NOT NULL,
  time_resolved time without time zone NULL,
  remarks text NULL,
  created_by_user_id bigint NULL REFERENCES public.users(id),
  updated_by_user_id bigint NULL REFERENCES public.users(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT case_resolutions_recommendation_code_check CHECK (recommendation_code IN ('CASE_FOR_FILING', 'CASE_DISMISSAL', 'MIXED_RESULT'))
);

CREATE TABLE IF NOT EXISTS public.case_resolution_charge_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_resolution_id bigint NOT NULL REFERENCES public.case_resolutions(id),
  case_id bigint NOT NULL REFERENCES public.cases(id),
  case_violation_id bigint NULL REFERENCES public.case_violations(id),
  violation_id bigint NULL REFERENCES public.violations(id),
  charge_text text NOT NULL,
  action_code text NOT NULL,
  display_order integer DEFAULT 0,
  remarks text NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT case_resolution_charge_actions_action_code_check CHECK (action_code IN ('FOR_FILING', 'DISMISSAL'))
);

CREATE INDEX IF NOT EXISTS idx_case_resolutions_case_id ON public.case_resolutions(case_id);
CREATE INDEX IF NOT EXISTS idx_case_resolution_charge_actions_resolution_id ON public.case_resolution_charge_actions(case_resolution_id);

CREATE OR REPLACE FUNCTION public.record_case_resolved_event(
  p_case_id bigint,
  p_recommendation_code text,
  p_date_resolved date,
  p_time_resolved time without time zone DEFAULT NULL,
  p_remarks text DEFAULT NULL,
  p_charges_for_filing jsonb DEFAULT '[]'::jsonb,
  p_charges_for_dismissal jsonb DEFAULT '[]'::jsonb,
  p_user_id bigint DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_type_id bigint;
  v_resolved_status_id bigint;
  v_previous_status_id bigint;
  v_event_id bigint;
  v_resolution_id bigint;
  v_status_history_id bigint;
  v_recommendation_label text;
  v_remarks text := NULLIF(btrim(COALESCE(p_remarks, '')), '');
  v_old_details jsonb;
  v_new_details jsonb;
  v_charge jsonb;
  v_display_order integer;
BEGIN
  IF p_case_id IS NULL THEN RAISE EXCEPTION 'Case id is required'; END IF;
  IF p_recommendation_code NOT IN ('CASE_FOR_FILING', 'CASE_DISMISSAL', 'MIXED_RESULT') THEN RAISE EXCEPTION 'Recommendation is required'; END IF;
  IF p_date_resolved IS NULL THEN RAISE EXCEPTION 'Date resolved is required'; END IF;

  IF NOT EXISTS (SELECT 1 FROM public.cases WHERE id = p_case_id) THEN
    RAISE EXCEPTION 'Unknown case id %', p_case_id;
  END IF;

  INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
  VALUES ('CASE_RESOLVED', 'Case Resolved', 'CASE', 'Manual timeline event for resolving a case.', 120, true, true)
  ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, category = EXCLUDED.category, description = EXCLUDED.description, sort_order = EXCLUDED.sort_order, is_active = true, updated_at = now()
  RETURNING id INTO v_event_type_id;

  INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
  VALUES ('RESOLVED', 'Resolved', 80, true, true, true)
  ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, is_final = true, is_milestone = true, is_active = true, updated_at = now()
  RETURNING id INTO v_resolved_status_id;

  v_recommendation_label := CASE p_recommendation_code
    WHEN 'CASE_FOR_FILING' THEN 'Case for Filing'
    WHEN 'CASE_DISMISSAL' THEN 'Case Dismissal'
    ELSE 'Mixed Result'
  END;

  SELECT cpd.current_status_id, to_jsonb(cpd)
  INTO v_previous_status_id, v_old_details
  FROM public.case_private_details cpd
  WHERE cpd.case_id = p_case_id;

  INSERT INTO public.case_events (
    case_id, event_type_id, event_date, event_time, title, description, status_id,
    details_jsonb, source, created_by_user_id, updated_by_user_id
  ) VALUES (
    p_case_id, v_event_type_id, p_date_resolved, p_time_resolved, 'Case Resolved',
    'Case resolved as ' || v_recommendation_label || ' on ' || to_char(p_date_resolved, 'Mon FMDD, YYYY'),
    v_resolved_status_id,
    jsonb_build_object('recommendation_code', p_recommendation_code, 'recommendation_label', v_recommendation_label, 'remarks', v_remarks),
    'MANUAL_ENTRY', p_user_id, p_user_id
  ) RETURNING id INTO v_event_id;

  INSERT INTO public.case_resolutions (case_id, case_event_id, recommendation_code, date_resolved, time_resolved, remarks, created_by_user_id, updated_by_user_id)
  VALUES (p_case_id, v_event_id, p_recommendation_code, p_date_resolved, p_time_resolved, v_remarks, p_user_id, p_user_id)
  RETURNING id INTO v_resolution_id;

  IF p_recommendation_code IN ('CASE_FOR_FILING', 'MIXED_RESULT') THEN
    v_display_order := 0;
    FOR v_charge IN SELECT * FROM jsonb_array_elements(COALESCE(p_charges_for_filing, '[]'::jsonb)) LOOP
      v_display_order := v_display_order + 1;
      IF NULLIF(btrim(COALESCE(v_charge->>'charge_text', v_charge #>> '{}')), '') IS NOT NULL THEN
        INSERT INTO public.case_resolution_charge_actions (case_resolution_id, case_id, case_violation_id, violation_id, charge_text, action_code, display_order, remarks)
        VALUES (v_resolution_id, p_case_id, NULLIF(v_charge->>'case_violation_id', '')::bigint, NULLIF(v_charge->>'violation_id', '')::bigint, NULLIF(btrim(COALESCE(v_charge->>'charge_text', v_charge #>> '{}')), ''), 'FOR_FILING', v_display_order, NULLIF(btrim(COALESCE(v_charge->>'remarks', '')), ''));
      END IF;
    END LOOP;
  END IF;

  IF p_recommendation_code IN ('CASE_DISMISSAL', 'MIXED_RESULT') THEN
    v_display_order := 0;
    FOR v_charge IN SELECT * FROM jsonb_array_elements(COALESCE(p_charges_for_dismissal, '[]'::jsonb)) LOOP
      v_display_order := v_display_order + 1;
      IF NULLIF(btrim(COALESCE(v_charge->>'charge_text', v_charge #>> '{}')), '') IS NOT NULL THEN
        INSERT INTO public.case_resolution_charge_actions (case_resolution_id, case_id, case_violation_id, violation_id, charge_text, action_code, display_order, remarks)
        VALUES (v_resolution_id, p_case_id, NULLIF(v_charge->>'case_violation_id', '')::bigint, NULLIF(v_charge->>'violation_id', '')::bigint, NULLIF(btrim(COALESCE(v_charge->>'charge_text', v_charge #>> '{}')), ''), 'DISMISSAL', v_display_order, NULLIF(btrim(COALESCE(v_charge->>'remarks', '')), ''));
      END IF;
    END LOOP;
  END IF;

  UPDATE public.case_events
  SET source_table = 'case_resolutions',
      source_id = v_resolution_id,
      details_jsonb = details_jsonb || jsonb_build_object(
        'charge_actions',
        COALESCE((
          SELECT jsonb_agg(jsonb_build_object(
            'id', cra.id,
            'action_code', cra.action_code,
            'charge_text', cra.charge_text,
            'display_order', cra.display_order,
            'remarks', cra.remarks
          ) ORDER BY cra.action_code, cra.display_order, cra.id)
          FROM public.case_resolution_charge_actions cra
          WHERE cra.case_resolution_id = v_resolution_id
        ), '[]'::jsonb)
      ),
      updated_by_user_id = p_user_id,
      updated_at = now()
  WHERE id = v_event_id;

  INSERT INTO public.case_private_details (case_id, current_status_id, current_status_date, current_status_remarks, updated_at)
  VALUES (p_case_id, v_resolved_status_id, p_date_resolved, v_remarks, now())
  ON CONFLICT (case_id) DO UPDATE SET
    current_status_id = EXCLUDED.current_status_id,
    current_status_date = EXCLUDED.current_status_date,
    current_status_remarks = EXCLUDED.current_status_remarks,
    updated_at = now();

  INSERT INTO public.case_status_history (case_id, from_status_id, to_status_id, changed_by_user_id, changed_at, status_date, remarks, case_event_id)
  VALUES (p_case_id, v_previous_status_id, v_resolved_status_id, p_user_id, now(), p_date_resolved, v_remarks, v_event_id)
  RETURNING id INTO v_status_history_id;

  SELECT to_jsonb(cpd) INTO v_new_details FROM public.case_private_details cpd WHERE cpd.case_id = p_case_id;

  INSERT INTO public.audit_logs (actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata)
  VALUES (p_user_id, 'case_resolutions', v_resolution_id, 'CASE_RESOLVED', v_old_details, v_new_details, p_case_id, 'Case resolved as ' || v_recommendation_label || '.', jsonb_build_object('case_event_id', v_event_id, 'status_history_id', v_status_history_id, 'recommendation_code', p_recommendation_code));

  RETURN v_event_id;
END;
$$;
