BEGIN;

INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
VALUES
  ('PETITION_FOR_REVIEW', 'Petition for Review', 'PETITION', 'Manual timeline event for a petition for review.', 170, true, true),
  ('PETITION_FOR_REVIEW_UPDATE', 'Petition for Review Update', 'PETITION', 'In-place update workflow for a petition for review.', 171, true, true)
ON CONFLICT (code) DO UPDATE SET display_label=EXCLUDED.display_label, category=EXCLUDED.category, description=EXCLUDED.description, sort_order=EXCLUDED.sort_order, is_active=true, updated_at=now();

INSERT INTO public.case_stages (code, display_label, sort_order, is_active)
VALUES ('PENDING_PETREV', 'Pending Petrev', 171, true)
ON CONFLICT (code) DO UPDATE SET display_label=EXCLUDED.display_label, is_active=true, updated_at=now();

ALTER TABLE public.case_petitions_for_review
  ADD COLUMN IF NOT EXISTS filed_by_code text,
  ADD COLUMN IF NOT EXISTS date_filed date,
  ADD COLUMN IF NOT EXISTS time_filed time without time zone,
  ADD COLUMN IF NOT EXISTS status_date date,
  ADD COLUMN IF NOT EXISTS additional_details_jsonb jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS assigned_prosecutor_id bigint REFERENCES public.prosecutors(id),
  ADD COLUMN IF NOT EXISTS is_voided boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS voided_at timestamptz,
  ADD COLUMN IF NOT EXISTS voided_by_user_id bigint REFERENCES public.users(id),
  ADD COLUMN IF NOT EXISTS void_reason text;

DO $$ BEGIN
  ALTER TABLE public.case_petitions_for_review ADD CONSTRAINT case_petitions_for_review_filed_by_code_chk CHECK (filed_by_code IS NULL OR filed_by_code IN ('COMPLAINANT','RESPONDENT'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_case_petitions_review_case_active ON public.case_petitions_for_review(case_id, is_voided, date_filed DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.case_petition_for_review_updates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  petition_for_review_id bigint NOT NULL REFERENCES public.case_petitions_for_review(id) ON DELETE CASCADE,
  petition_status text NOT NULL,
  status_date date NOT NULL,
  remarks text,
  additional_details_jsonb jsonb NOT NULL DEFAULT '[]'::jsonb,
  updates_case_status boolean NOT NULL DEFAULT false,
  selected_case_status_id bigint REFERENCES public.case_statuses(id),
  selected_case_stage_id bigint REFERENCES public.case_stages(id),
  created_by_user_id bigint REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_voided boolean NOT NULL DEFAULT false,
  voided_at timestamptz,
  voided_by_user_id bigint REFERENCES public.users(id),
  void_reason text
);
CREATE INDEX IF NOT EXISTS idx_case_petrev_updates_petition_active ON public.case_petition_for_review_updates(petition_for_review_id, is_voided, status_date DESC, id DESC);
GRANT ALL ON TABLE public.case_petition_for_review_updates TO authenticated, service_role;
GRANT ALL ON SEQUENCE public.case_petition_for_review_updates_id_seq TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.normalize_petition_details(p_details jsonb)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE v_details jsonb := '[]'::jsonb; v_item jsonb;
BEGIN
  IF p_details IS NOT NULL AND jsonb_typeof(p_details) <> 'array' THEN RAISE EXCEPTION 'Additional Details must be a JSON array'; END IF;
  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_details,'[]'::jsonb)) LOOP
    IF nullif(btrim(v_item->>'detail'), '') IS NOT NULL OR nullif(btrim(v_item->>'value'), '') IS NOT NULL THEN
      v_details := v_details || jsonb_build_array(jsonb_build_object('detail', btrim(coalesce(v_item->>'detail','')), 'value', btrim(coalesce(v_item->>'value',''))));
    END IF;
  END LOOP;
  RETURN v_details;
END;
$$;

CREATE OR REPLACE FUNCTION public.compute_current_case_state(p_case_id bigint)
RETURNS TABLE(case_status_code text, case_stage_code text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_active_petition_count integer; v_petition_status_code text; v_petition_stage_code text;
  v_motion_resolution_for_approval_count integer; v_pending_motion_count integer; v_unapproved_resolution_count integer; v_unfiled_for_filing_count integer; v_filed_for_filing_count integer; v_dismissal_count integer; v_active_assignment_count integer; v_manual_status_code text; v_manual_stage_code text;
BEGIN
  SELECT cs.code, cst.code INTO v_petition_status_code, v_petition_stage_code
  FROM public.case_petition_for_review_updates u
  JOIN public.case_petitions_for_review p ON p.id=u.petition_for_review_id AND p.is_voided=false
  JOIN public.case_events pe ON pe.id=p.case_event_id AND pe.is_voided=false
  JOIN public.case_statuses cs ON cs.id=u.selected_case_status_id AND cs.is_active IS TRUE
  JOIN public.case_stages cst ON cst.id=u.selected_case_stage_id AND cst.is_active IS TRUE
  WHERE u.case_id=p_case_id AND u.is_voided=false AND u.updates_case_status=true
  ORDER BY u.status_date DESC, u.id DESC LIMIT 1;
  IF v_petition_status_code IS NOT NULL THEN RETURN QUERY SELECT v_petition_status_code, v_petition_stage_code; RETURN; END IF;

  SELECT count(*) INTO v_active_petition_count FROM public.case_petitions_for_review p JOIN public.case_events ce ON ce.id=p.case_event_id AND ce.is_voided=false WHERE p.case_id=p_case_id AND p.is_voided=false;
  IF COALESCE(v_active_petition_count,0) > 0 THEN RETURN QUERY SELECT 'PENDING'::text, 'PENDING_PETREV'::text; RETURN; END IF;

  SELECT count(*) INTO v_motion_resolution_for_approval_count FROM public.case_motion_resolutions cmr JOIN public.case_motions cm ON cm.id=cmr.case_motion_id AND cm.is_voided=false JOIN public.case_events re ON re.id=cmr.case_event_id AND re.is_voided=false JOIN public.case_events me ON me.id=cm.case_event_id AND me.is_voided=false WHERE cmr.case_id=p_case_id AND cmr.is_voided=false AND NOT EXISTS (SELECT 1 FROM public.case_motion_resolution_approvals a JOIN public.case_events ae ON ae.id=a.case_event_id AND ae.is_voided=false WHERE a.case_motion_resolution_id=cmr.id AND a.is_voided=false);
  SELECT count(*) INTO v_pending_motion_count FROM public.case_motions cm JOIN public.case_events ce ON ce.id=cm.case_event_id AND ce.is_voided=false WHERE cm.case_id=p_case_id AND cm.is_voided=false AND cm.case_event_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.case_motion_resolutions cmr WHERE cmr.case_motion_id=cm.id AND cmr.is_voided=false);
  IF COALESCE(v_motion_resolution_for_approval_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'MOTION_RESO_FOR_APPROVAL'::text; RETURN; ELSIF COALESCE(v_pending_motion_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'MOTION_PENDING'::text; RETURN; END IF;
  SELECT count(*) INTO v_unapproved_resolution_count FROM public.case_resolutions cr WHERE cr.case_id=p_case_id AND cr.is_voided=false AND NOT EXISTS (SELECT 1 FROM public.case_resolution_approvals a WHERE a.case_resolution_id=cr.id AND a.is_voided=false);
  SELECT count(*) FILTER (WHERE aa.decision_code='FOR_FILING' AND EXISTS (SELECT 1 FROM public.case_court_filings cf WHERE cf.case_resolution_approval_action_id=aa.id AND cf.is_voided=false)), count(*) FILTER (WHERE aa.decision_code='FOR_FILING' AND NOT EXISTS (SELECT 1 FROM public.case_court_filings cf WHERE cf.case_resolution_approval_action_id=aa.id AND cf.is_voided=false)), count(*) FILTER (WHERE aa.decision_code='DISMISSAL') INTO v_filed_for_filing_count, v_unfiled_for_filing_count, v_dismissal_count FROM public.case_resolution_approval_actions aa JOIN public.case_resolution_approvals a ON a.id=aa.approval_id AND a.is_voided=false JOIN public.case_resolutions cr ON cr.id=a.case_resolution_id AND cr.is_voided=false WHERE aa.case_id=p_case_id;
  IF COALESCE(v_unapproved_resolution_count,0)>0 THEN IF COALESCE(v_filed_for_filing_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'FILED_OTHER_RESO_FOR_APPROVAL'::text; ELSE RETURN QUERY SELECT 'PENDING'::text,'RESO_FOR_APPROVAL'::text; END IF; RETURN; ELSIF COALESCE(v_unfiled_for_filing_count,0)>0 THEN IF COALESCE(v_filed_for_filing_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'FILED_OTHER_INFO_FOR_FILING'::text; ELSE RETURN QUERY SELECT 'PENDING'::text,'FOR_FILING'::text; END IF; RETURN; END IF;
  SELECT cs.code,cst.code INTO v_manual_status_code,v_manual_stage_code FROM public.case_motion_resolution_approvals a JOIN public.case_events ce ON ce.id=a.case_event_id AND ce.is_voided=false JOIN public.case_statuses cs ON cs.id=a.selected_case_status_id AND cs.is_active IS TRUE JOIN public.case_stages cst ON cst.id=a.selected_case_stage_id AND cst.is_active IS TRUE JOIN public.case_motion_resolutions r ON r.id=a.case_motion_resolution_id AND r.is_voided=false JOIN public.case_motions m ON m.id=a.case_motion_id AND m.is_voided=false WHERE a.case_id=p_case_id AND a.is_voided=false AND a.updates_case_status=true ORDER BY a.date_approved DESC NULLS LAST, a.time_approved DESC NULLS LAST, a.case_event_id DESC, a.id DESC LIMIT 1;
  IF v_manual_status_code IS NOT NULL THEN RETURN QUERY SELECT v_manual_status_code,v_manual_stage_code; RETURN; END IF;
  SELECT count(*) INTO v_active_assignment_count FROM public.case_assignments ca WHERE ca.case_id=p_case_id AND ca.unassigned_at IS NULL AND ca.is_voided IS FALSE;
  IF COALESCE(v_filed_for_filing_count,0)>0 AND COALESCE(v_dismissal_count,0)>0 THEN RETURN QUERY SELECT 'MIXED_RESULT'::text,'MIXED_RESULT'::text; ELSIF COALESCE(v_filed_for_filing_count,0)>0 THEN RETURN QUERY SELECT 'FILED'::text,'FILED'::text; ELSIF COALESCE(v_dismissal_count,0)>0 THEN RETURN QUERY SELECT 'DISMISSED'::text,'DISMISSED'::text; ELSIF COALESCE(v_active_assignment_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'CASE_RAFFLED'::text; ELSE RETURN QUERY SELECT 'PENDING'::text,'FOR_RAFFLE'::text; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_petition_for_review_event(p_case_id bigint,p_filed_by_code text,p_date_filed date,p_time_filed time without time zone DEFAULT NULL,p_petition_status text DEFAULT NULL,p_additional_details_jsonb jsonb DEFAULT '[]'::jsonb,p_assigned_prosecutor_id bigint DEFAULT NULL,p_remarks text DEFAULT NULL,p_user_id bigint DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_event_type_id bigint; v_event_id bigint; v_petition_id bigint; v_status_id bigint; v_stage_id bigint; v_prev_status_id bigint; v_prev_stage_id bigint; v_status_history_id bigint; v_stage_history_id bigint; v_details jsonb; v_assigned bigint; v_assigned_name text; v_old jsonb; v_new jsonb; v_time time; v_filed_by_label text; v_status text := nullif(btrim(coalesce(p_petition_status,'')), ''); v_remarks text := nullif(btrim(coalesce(p_remarks,'')), '');
BEGIN
  IF p_case_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.cases WHERE id=p_case_id) THEN RAISE EXCEPTION 'Unknown case id %', p_case_id; END IF;
  IF p_date_filed IS NULL THEN RAISE EXCEPTION 'Date Filed is required'; END IF;
  IF p_filed_by_code NOT IN ('COMPLAINANT','RESPONDENT') THEN RAISE EXCEPTION 'Filed By must be COMPLAINANT or RESPONDENT'; END IF;
  IF v_status IS NULL THEN RAISE EXCEPTION 'Status is required'; END IF;
  v_filed_by_label := CASE p_filed_by_code WHEN 'COMPLAINANT' THEN 'Complainant' ELSE 'Respondent' END;
  v_details := public.normalize_petition_details(p_additional_details_jsonb);
  v_time := coalesce(p_time_filed, (now() AT TIME ZONE 'Asia/Manila')::time(0));
  SELECT coalesce(p_assigned_prosecutor_id, ca.prosecutor_id) INTO v_assigned FROM public.case_assignments ca WHERE ca.case_id=p_case_id AND ca.unassigned_at IS NULL AND ca.is_voided=false ORDER BY ca.assigned_at DESC NULLS LAST, ca.id DESC LIMIT 1;
  IF p_assigned_prosecutor_id IS NOT NULL THEN v_assigned := p_assigned_prosecutor_id; END IF;
  SELECT coalesce(short_name,full_name) INTO v_assigned_name FROM public.prosecutors WHERE id=v_assigned;
  SELECT id INTO v_event_type_id FROM public.case_event_types WHERE code='PETITION_FOR_REVIEW' AND is_active IS TRUE LIMIT 1;
  SELECT id INTO v_status_id FROM public.case_statuses WHERE code='PENDING' AND is_active IS TRUE LIMIT 1;
  SELECT id INTO v_stage_id FROM public.case_stages WHERE code='PENDING_PETREV' AND is_active IS TRUE LIMIT 1;
  IF v_event_type_id IS NULL OR v_status_id IS NULL OR v_stage_id IS NULL THEN RAISE EXCEPTION 'Missing Petition for Review seed data'; END IF;
  SELECT current_status_id,current_case_stage_id,to_jsonb(cpd) INTO v_prev_status_id,v_prev_stage_id,v_old FROM public.case_private_details cpd WHERE case_id=p_case_id;
  INSERT INTO public.case_events(case_id,event_type_id,event_date,event_time,title,description,status_id,case_status_id,case_stage_id,details_jsonb,source,source_table,created_by_user_id,updated_by_user_id) VALUES (p_case_id,v_event_type_id,p_date_filed,v_time,'Petition for Review',v_remarks,v_status_id,v_status_id,v_stage_id,jsonb_build_object('filed_by_code',p_filed_by_code,'filed_by_label',v_filed_by_label,'date_filed',p_date_filed,'time_filed',v_time,'petition_status',v_status,'status_date',p_date_filed,'additional_details',v_details,'assigned_prosecutor_id',v_assigned,'assigned_prosecutor_name',v_assigned_name,'remarks',v_remarks),'MANUAL_ENTRY','case_petitions_for_review',p_user_id,p_user_id) RETURNING id INTO v_event_id;
  INSERT INTO public.case_petitions_for_review(case_id,case_event_id,petition_title,filed_by,filed_by_code,date_received,date_filed,time_filed,petition_status,status_date,additional_details_jsonb,assigned_prosecutor_id,handling_prosecutor_text,remarks,source,created_by_user_id,updated_by_user_id) VALUES (p_case_id,v_event_id,'Petition for Review',v_filed_by_label,p_filed_by_code,p_date_filed,p_date_filed,v_time,v_status,p_date_filed,v_details,v_assigned,v_assigned_name,v_remarks,'MANUAL_ENTRY',p_user_id,p_user_id) RETURNING id INTO v_petition_id;
  UPDATE public.case_events SET source_id=v_petition_id, details_jsonb=details_jsonb || jsonb_build_object('petition_for_review_id',v_petition_id) WHERE id=v_event_id;
  INSERT INTO public.case_private_details(case_id,current_status_id,current_status_date,current_status_remarks,current_case_status_id,current_case_status_date,current_case_status_remarks,current_case_stage_id,current_case_stage_date,current_case_stage_remarks,updated_at) VALUES(p_case_id,v_status_id,p_date_filed,v_remarks,v_status_id,p_date_filed,v_remarks,v_stage_id,p_date_filed,v_remarks,now()) ON CONFLICT(case_id) DO UPDATE SET current_status_id=EXCLUDED.current_status_id,current_status_date=EXCLUDED.current_status_date,current_status_remarks=EXCLUDED.current_status_remarks,current_case_status_id=EXCLUDED.current_case_status_id,current_case_status_date=EXCLUDED.current_case_status_date,current_case_status_remarks=EXCLUDED.current_case_status_remarks,current_case_stage_id=EXCLUDED.current_case_stage_id,current_case_stage_date=EXCLUDED.current_case_stage_date,current_case_stage_remarks=EXCLUDED.current_case_stage_remarks,updated_at=now();
  IF v_prev_status_id IS DISTINCT FROM v_status_id THEN INSERT INTO public.case_status_history(case_id,from_status_id,to_status_id,changed_by_user_id,changed_at,status_date,remarks,case_event_id) VALUES(p_case_id,v_prev_status_id,v_status_id,p_user_id,now(),p_date_filed,v_remarks,v_event_id) RETURNING id INTO v_status_history_id; END IF;
  IF v_prev_stage_id IS DISTINCT FROM v_stage_id THEN INSERT INTO public.case_stage_history(case_id,from_stage_id,to_stage_id,changed_by_user_id,changed_at,stage_date,remarks,case_event_id) VALUES(p_case_id,v_prev_stage_id,v_stage_id,p_user_id,now(),p_date_filed,v_remarks,v_event_id) RETURNING id INTO v_stage_history_id; END IF;
  SELECT to_jsonb(cpd) INTO v_new FROM public.case_private_details cpd WHERE case_id=p_case_id;
  INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata) VALUES(p_user_id,'case_petitions_for_review',v_petition_id,'PETITION_FOR_REVIEW',v_old,v_new,p_case_id,'Petition for Review recorded.',jsonb_build_object('case_event_id',v_event_id,'status_history_id',v_status_history_id,'case_stage_history_id',v_stage_history_id));
  RETURN v_event_id;
END; $$;
GRANT EXECUTE ON FUNCTION public.record_petition_for_review_event(bigint,text,date,time without time zone,text,jsonb,bigint,text,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.update_petition_event_details(p_petition_id bigint,p_user_id bigint DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE p public.case_petitions_for_review%ROWTYPE; v_name text;
BEGIN
 SELECT * INTO p FROM public.case_petitions_for_review WHERE id=p_petition_id;
 IF p.id IS NULL OR p.case_event_id IS NULL THEN RETURN; END IF;
 SELECT coalesce(short_name,full_name) INTO v_name FROM public.prosecutors WHERE id=p.assigned_prosecutor_id;
 UPDATE public.case_events SET details_jsonb=coalesce(details_jsonb,'{}'::jsonb)||jsonb_build_object('petition_for_review_id',p.id,'filed_by_code',p.filed_by_code,'filed_by_label',p.filed_by,'date_filed',p.date_filed,'time_filed',p.time_filed,'petition_status',p.petition_status,'status_date',p.status_date,'additional_details',p.additional_details_jsonb,'assigned_prosecutor_id',p.assigned_prosecutor_id,'assigned_prosecutor_name',coalesce(v_name,p.handling_prosecutor_text),'remarks',p.remarks), updated_at=now(), updated_by_user_id=p_user_id WHERE id=p.case_event_id;
END; $$;

CREATE OR REPLACE FUNCTION public.record_petition_for_review_update(p_case_id bigint,p_petition_for_review_id bigint,p_petition_status text,p_status_date date,p_remarks text DEFAULT NULL,p_additional_details_jsonb jsonb DEFAULT '[]'::jsonb,p_updates_case_status boolean DEFAULT false,p_selected_case_status_id bigint DEFAULT NULL,p_selected_case_stage_id bigint DEFAULT NULL,p_user_id bigint DEFAULT NULL) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_update_id bigint; v_details jsonb; v_old jsonb; v_new jsonb; v_status_id bigint; v_stage_id bigint; v_prev_status_id bigint; v_prev_stage_id bigint; v_status_history_id bigint; v_stage_history_id bigint; v_status_code text; v_stage_code text; v_remarks text:=nullif(btrim(coalesce(p_remarks,'')), '');
BEGIN
 IF nullif(btrim(coalesce(p_petition_status,'')), '') IS NULL THEN RAISE EXCEPTION 'Petition Status is required'; END IF;
 IF p_status_date IS NULL THEN RAISE EXCEPTION 'Status Date is required'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.case_petitions_for_review p JOIN public.case_events ce ON ce.id=p.case_event_id AND ce.is_voided=false WHERE p.id=p_petition_for_review_id AND p.case_id=p_case_id AND p.is_voided=false) THEN RAISE EXCEPTION 'Selected Petition for Review is not active for this case'; END IF;
 v_details := public.normalize_petition_details(p_additional_details_jsonb);
 IF p_updates_case_status THEN IF p_selected_case_status_id IS NULL OR p_selected_case_stage_id IS NULL THEN RAISE EXCEPTION 'Case Status and Case Stage are required'; END IF; SELECT code INTO v_status_code FROM public.case_statuses WHERE id=p_selected_case_status_id AND is_active IS TRUE; SELECT code INTO v_stage_code FROM public.case_stages WHERE id=p_selected_case_stage_id AND is_active IS TRUE; IF v_status_code IS NULL OR v_stage_code IS NULL THEN RAISE EXCEPTION 'Selected Case Status and Case Stage must be active'; END IF; ELSE SELECT id INTO p_selected_case_status_id FROM public.case_statuses WHERE code='PENDING' AND is_active IS TRUE; SELECT id INTO p_selected_case_stage_id FROM public.case_stages WHERE code='PENDING_PETREV' AND is_active IS TRUE; END IF;
 SELECT current_status_id,current_case_stage_id,to_jsonb(cpd) INTO v_prev_status_id,v_prev_stage_id,v_old FROM public.case_private_details cpd WHERE case_id=p_case_id;
 INSERT INTO public.case_petition_for_review_updates(case_id,petition_for_review_id,petition_status,status_date,remarks,additional_details_jsonb,updates_case_status,selected_case_status_id,selected_case_stage_id,created_by_user_id) VALUES(p_case_id,p_petition_for_review_id,btrim(p_petition_status),p_status_date,v_remarks,v_details,p_updates_case_status,CASE WHEN p_updates_case_status THEN p_selected_case_status_id ELSE NULL END,CASE WHEN p_updates_case_status THEN p_selected_case_stage_id ELSE NULL END,p_user_id) RETURNING id INTO v_update_id;
 UPDATE public.case_petitions_for_review SET petition_status=btrim(p_petition_status), status_date=p_status_date, remarks=v_remarks, additional_details_jsonb=v_details, updated_at=now(), updated_by_user_id=p_user_id WHERE id=p_petition_for_review_id;
 v_status_id:=p_selected_case_status_id; v_stage_id:=p_selected_case_stage_id;
 INSERT INTO public.case_private_details(case_id,current_status_id,current_status_date,current_status_remarks,current_case_status_id,current_case_status_date,current_case_status_remarks,current_case_stage_id,current_case_stage_date,current_case_stage_remarks,updated_at) VALUES(p_case_id,v_status_id,p_status_date,v_remarks,v_status_id,p_status_date,v_remarks,v_stage_id,p_status_date,v_remarks,now()) ON CONFLICT(case_id) DO UPDATE SET current_status_id=EXCLUDED.current_status_id,current_status_date=EXCLUDED.current_status_date,current_status_remarks=EXCLUDED.current_status_remarks,current_case_status_id=EXCLUDED.current_case_status_id,current_case_status_date=EXCLUDED.current_case_status_date,current_case_status_remarks=EXCLUDED.current_case_status_remarks,current_case_stage_id=EXCLUDED.current_case_stage_id,current_case_stage_date=EXCLUDED.current_case_stage_date,current_case_stage_remarks=EXCLUDED.current_case_stage_remarks,updated_at=now();
 IF v_prev_status_id IS DISTINCT FROM v_status_id THEN INSERT INTO public.case_status_history(case_id,from_status_id,to_status_id,changed_by_user_id,changed_at,status_date,remarks) VALUES(p_case_id,v_prev_status_id,v_status_id,p_user_id,now(),p_status_date,v_remarks) RETURNING id INTO v_status_history_id; END IF;
 IF v_prev_stage_id IS DISTINCT FROM v_stage_id THEN INSERT INTO public.case_stage_history(case_id,from_stage_id,to_stage_id,changed_by_user_id,changed_at,stage_date,remarks) VALUES(p_case_id,v_prev_stage_id,v_stage_id,p_user_id,now(),p_status_date,v_remarks) RETURNING id INTO v_stage_history_id; END IF;
 PERFORM public.update_petition_event_details(p_petition_for_review_id,p_user_id);
 SELECT to_jsonb(cpd) INTO v_new FROM public.case_private_details cpd WHERE case_id=p_case_id;
 INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata) VALUES(p_user_id,'case_petition_for_review_updates',v_update_id,'PETITION_FOR_REVIEW_UPDATE',v_old,v_new,p_case_id,'Petition for Review update recorded.',jsonb_build_object('petition_for_review_id',p_petition_for_review_id,'updates_case_status',p_updates_case_status,'status_history_id',v_status_history_id,'case_stage_history_id',v_stage_history_id));
 RETURN v_update_id;
END; $$;
GRANT EXECUTE ON FUNCTION public.record_petition_for_review_update(bigint,bigint,text,date,text,jsonb,boolean,bigint,bigint,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.void_petition_for_review_update(p_update_id bigint,p_void_reason text,p_voided_by_user_id bigint DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE u public.case_petition_for_review_updates%ROWTYPE; prev public.case_petition_for_review_updates%ROWTYPE; p public.case_petitions_for_review%ROWTYPE; v_status_id bigint; v_stage_id bigint; v_old jsonb; v_new jsonb;
BEGIN
 IF nullif(trim(p_void_reason),'') IS NULL THEN RAISE EXCEPTION 'Void reason is required'; END IF;
 SELECT * INTO u FROM public.case_petition_for_review_updates WHERE id=p_update_id AND is_voided=false; IF u.id IS NULL THEN RAISE EXCEPTION 'Active Petition for Review Update not found'; END IF;
 IF EXISTS(SELECT 1 FROM public.case_petition_for_review_updates x WHERE x.petition_for_review_id=u.petition_for_review_id AND x.is_voided=false AND (x.status_date,x.id)>(u.status_date,u.id)) THEN RAISE EXCEPTION 'Only the latest active Petition for Review Update can be voided.'; END IF;
 SELECT * INTO p FROM public.case_petitions_for_review WHERE id=u.petition_for_review_id;
 SELECT to_jsonb(cpd) INTO v_old FROM public.case_private_details cpd WHERE case_id=u.case_id;
 UPDATE public.case_petition_for_review_updates SET is_voided=true, voided_at=now(), voided_by_user_id=p_voided_by_user_id, void_reason=p_void_reason, updated_at=now() WHERE id=u.id;
 SELECT * INTO prev FROM public.case_petition_for_review_updates WHERE petition_for_review_id=u.petition_for_review_id AND is_voided=false ORDER BY status_date DESC, id DESC LIMIT 1;
 IF prev.id IS NOT NULL THEN UPDATE public.case_petitions_for_review SET petition_status=prev.petition_status,status_date=prev.status_date,remarks=prev.remarks,additional_details_jsonb=prev.additional_details_jsonb,updated_at=now(),updated_by_user_id=p_voided_by_user_id WHERE id=p.id; IF prev.updates_case_status THEN v_status_id:=prev.selected_case_status_id; v_stage_id:=prev.selected_case_stage_id; END IF; ELSE UPDATE public.case_petitions_for_review SET petition_status=coalesce(p.petition_status,'Filed'),status_date=coalesce(p.date_filed,p.date_received),remarks=p.remarks,additional_details_jsonb=p.additional_details_jsonb,updated_at=now(),updated_by_user_id=p_voided_by_user_id WHERE id=p.id; END IF;
 IF v_status_id IS NULL THEN SELECT id INTO v_status_id FROM public.case_statuses WHERE code='PENDING' AND is_active IS TRUE; SELECT id INTO v_stage_id FROM public.case_stages WHERE code='PENDING_PETREV' AND is_active IS TRUE; END IF;
 UPDATE public.case_private_details SET current_status_id=v_status_id,current_status_date=CURRENT_DATE,current_case_status_id=v_status_id,current_case_status_date=CURRENT_DATE,current_case_stage_id=v_stage_id,current_case_stage_date=CURRENT_DATE,updated_at=now() WHERE case_id=u.case_id;
 PERFORM public.update_petition_event_details(u.petition_for_review_id,p_voided_by_user_id);
 SELECT to_jsonb(cpd) INTO v_new FROM public.case_private_details cpd WHERE case_id=u.case_id;
 INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata) VALUES(p_voided_by_user_id,'case_petition_for_review_updates',u.id,'VOID_PETITION_FOR_REVIEW_UPDATE',v_old,v_new,u.case_id,'Petition for Review update voided.',jsonb_build_object('petition_for_review_id',u.petition_for_review_id,'reason',p_void_reason,'previous_update_id',prev.id));
END; $$;
GRANT EXECUTE ON FUNCTION public.void_petition_for_review_update(bigint,text,bigint) TO authenticated;

DROP VIEW IF EXISTS public.v_case_petitions_for_review_detail;
CREATE VIEW public.v_case_petitions_for_review_detail AS
SELECT p.id,p.case_id,p.case_event_id,p.petition_title,p.handling_prosecutor_text,p.date_received,p.date_received_raw,p.filed_by,p.filed_by_code,p.date_filed,p.time_filed,p.petition_status,p.status_date,p.date_resolved,p.date_resolved_raw,p.date_approved,p.date_approved_raw,p.remarks,p.additional_details_jsonb,p.assigned_prosecutor_id,coalesce(pr.short_name,pr.full_name,p.handling_prosecutor_text) AS assigned_prosecutor_name,p.is_voided
FROM public.case_petitions_for_review p LEFT JOIN public.prosecutors pr ON pr.id=p.assigned_prosecutor_id;
GRANT SELECT ON public.v_case_petitions_for_review_detail TO authenticated, service_role;

-- public.void_case_event changed only for PETITION_FOR_REVIEW dependency guard/void and shared recompute.
CREATE OR REPLACE FUNCTION public.void_case_event(p_case_event_id bigint, p_void_reason text, p_voided_by_user_id bigint DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_old jsonb; v_new jsonb; v_case_id bigint; v_event_type_code text; v_source_table text; v_source_id bigint;
  v_filing_id bigint; v_filing_old jsonb; v_filing_new jsonb; v_approval_id bigint; v_resolution_id bigint;
  v_assignment_id bigint; v_assignment_old jsonb; v_assignment_new jsonb;
  v_motion_id bigint; v_motion_old jsonb; v_motion_new jsonb;
  v_petition_id bigint; v_petition_old jsonb; v_petition_new jsonb;
  v_motion_resolution_id bigint; v_motion_resolution_old jsonb; v_motion_resolution_new jsonb; v_motion_approval_count integer;
  v_motion_decision_approval_id bigint; v_motion_decision_approval_old jsonb; v_motion_decision_approval_new jsonb;
  v_previous_assignment_id bigint; v_previous_assignment_old jsonb; v_previous_assignment_new jsonb; v_latest_assignment_id bigint;
  v_status_code text; v_status_label text; v_status_id bigint; v_prev_status_id bigint; v_status_history_id bigint; v_old_details jsonb; v_new_details jsonb;
BEGIN
  IF nullif(trim(p_void_reason), '') IS NULL THEN RAISE EXCEPTION 'Void reason is required'; END IF;
  SELECT to_jsonb(ce), ce.case_id, cet.code, ce.source_table, ce.source_id INTO v_old, v_case_id, v_event_type_code, v_source_table, v_source_id
  FROM public.case_events ce LEFT JOIN public.case_event_types cet ON cet.id = ce.event_type_id WHERE ce.id = p_case_event_id AND ce.is_voided = false;
  IF v_old IS NULL THEN RAISE EXCEPTION 'Active case event % not found', p_case_event_id; END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_resolution_approvals' OR v_event_type_code = 'CASE_DECISION_APPROVED' THEN
    SELECT a.id INTO v_approval_id FROM public.case_resolution_approvals a WHERE a.id = v_source_id OR a.case_event_id = p_case_event_id LIMIT 1;
    IF v_approval_id IS NOT NULL AND EXISTS (SELECT 1 FROM public.case_court_filings cf JOIN public.case_resolution_approval_actions aa ON aa.id = cf.case_resolution_approval_action_id WHERE aa.approval_id = v_approval_id AND cf.is_voided = false) THEN
      RAISE EXCEPTION 'This approval has a court filing. Void the court filing first.';
    END IF;
  END IF;
  IF lower(coalesce(v_source_table,'')) = 'case_resolutions' OR v_event_type_code = 'CASE_RESOLVED' THEN
    SELECT cr.id INTO v_resolution_id FROM public.case_resolutions cr WHERE cr.id = v_source_id OR cr.case_event_id = p_case_event_id LIMIT 1;
    IF v_resolution_id IS NOT NULL AND EXISTS (SELECT 1 FROM public.case_court_filings cf JOIN public.case_resolution_approval_actions aa ON aa.id = cf.case_resolution_approval_action_id JOIN public.case_resolution_approvals a ON a.id = aa.approval_id WHERE a.case_resolution_id = v_resolution_id AND cf.is_voided = false) THEN
      RAISE EXCEPTION 'This resolution has a court filing. Void the court filing first.';
    END IF;
  END IF;

  SELECT current_status_id, to_jsonb(cpd) INTO v_prev_status_id, v_old_details FROM public.case_private_details cpd WHERE cpd.case_id = v_case_id;
  UPDATE public.case_events SET is_voided = true, void_reason = p_void_reason, voided_at = now(), voided_by_user_id = p_voided_by_user_id, updated_by_user_id = p_voided_by_user_id, updated_at = now() WHERE id = p_case_event_id;
  SELECT to_jsonb(ce) INTO v_new FROM public.case_events ce WHERE ce.id = p_case_event_id;
  INSERT INTO public.audit_logs(actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata) VALUES (p_voided_by_user_id, 'case_events', p_case_event_id, 'VOID_CASE_EVENT', v_old, v_new, v_case_id, 'Voided case timeline activity', jsonb_build_object('reason', p_void_reason));

  IF lower(coalesce(v_source_table,'')) = 'case_petitions_for_review' OR v_event_type_code = 'PETITION_FOR_REVIEW' THEN
    SELECT p.id, to_jsonb(p) INTO v_petition_id, v_petition_old
    FROM public.case_petitions_for_review p
    WHERE p.id = v_source_id OR p.case_event_id = p_case_event_id
    ORDER BY CASE WHEN p.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;
    IF v_petition_id IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.case_petition_for_review_updates u WHERE u.petition_for_review_id = v_petition_id AND u.is_voided = false) THEN
        RAISE EXCEPTION 'This Petition for Review has active updates. Void the latest Petition for Review Update first.';
      END IF;
      UPDATE public.case_petitions_for_review
      SET is_voided = true, voided_at = now(), voided_by_user_id = p_voided_by_user_id, void_reason = p_void_reason, updated_by_user_id = p_voided_by_user_id, updated_at = now()
      WHERE id = v_petition_id;
      SELECT to_jsonb(p) INTO v_petition_new FROM public.case_petitions_for_review p WHERE p.id = v_petition_id;
      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);
      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_petitions_for_review',v_petition_id,'VOID_PETITION_FOR_REVIEW_FROM_EVENT',v_petition_old,v_petition_new,v_case_id,'Petition for Review voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_motions' OR v_event_type_code = 'MOTION_RECEIVED' THEN
    SELECT cm.id, to_jsonb(cm) INTO v_motion_id, v_motion_old FROM public.case_motions cm WHERE cm.id = v_source_id OR cm.case_event_id = p_case_event_id ORDER BY CASE WHEN cm.id = v_source_id THEN 0 ELSE 1 END LIMIT 1;
    IF v_motion_id IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.case_motion_resolutions cmr WHERE cmr.case_motion_id = v_motion_id AND cmr.is_voided = false) THEN
        RAISE EXCEPTION 'This motion already has a resolution. Void the motion resolution first.';
      END IF;
      UPDATE public.case_motions SET is_voided = true, voided_at = now(), voided_by_user_id = p_voided_by_user_id, void_reason = p_void_reason, updated_by_user_id = p_voided_by_user_id, updated_at = now() WHERE id = v_motion_id;
      SELECT to_jsonb(cm) INTO v_motion_new FROM public.case_motions cm WHERE cm.id = v_motion_id;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_motions',v_motion_id,'VOID_MOTION_RECEIVED_FROM_EVENT',v_motion_old,v_motion_new,v_case_id,'Motion Received voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_motion_resolution_approvals' OR v_event_type_code = 'MOTION_DECISION_APPROVED' THEN
    SELECT cmra.id, to_jsonb(cmra) INTO v_motion_decision_approval_id, v_motion_decision_approval_old
    FROM public.case_motion_resolution_approvals cmra
    WHERE cmra.id = v_source_id OR cmra.case_event_id = p_case_event_id
    ORDER BY CASE WHEN cmra.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_motion_decision_approval_id IS NOT NULL THEN
      UPDATE public.case_motion_resolution_approvals
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      WHERE id = v_motion_decision_approval_id;

      SELECT to_jsonb(cmra) INTO v_motion_decision_approval_new
      FROM public.case_motion_resolution_approvals cmra
      WHERE cmra.id = v_motion_decision_approval_id;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_motion_resolution_approvals',v_motion_decision_approval_id,'VOID_MOTION_DECISION_APPROVED_FROM_EVENT',v_motion_decision_approval_old,v_motion_decision_approval_new,v_case_id,'Motion Decision Approved voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_motion_resolutions' OR v_event_type_code = 'MOTION_RESOLVED' THEN
    SELECT cmr.id, to_jsonb(cmr) INTO v_motion_resolution_id, v_motion_resolution_old
    FROM public.case_motion_resolutions cmr
    WHERE cmr.id = v_source_id OR cmr.case_event_id = p_case_event_id
    ORDER BY CASE WHEN cmr.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_motion_resolution_id IS NOT NULL THEN
      SELECT count(*) INTO v_motion_approval_count
      FROM public.case_motion_resolution_approvals cmra
      WHERE cmra.case_motion_resolution_id = v_motion_resolution_id
        AND cmra.is_voided = false;
      IF COALESCE(v_motion_approval_count, 0) > 0 THEN
        RAISE EXCEPTION 'This motion resolution already has an approved decision. Void the approval event first.';
      END IF;

      UPDATE public.case_motion_resolutions
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      WHERE id = v_motion_resolution_id;

      SELECT to_jsonb(cmr) INTO v_motion_resolution_new
      FROM public.case_motion_resolutions cmr
      WHERE cmr.id = v_motion_resolution_id;

      UPDATE public.case_motions cm
      SET motion_status = 'PENDING',
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      FROM public.case_motion_resolutions cmr
      WHERE cm.id = cmr.case_motion_id
        AND cmr.id = v_motion_resolution_id
        AND cm.is_voided = false;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_motion_resolutions',v_motion_resolution_id,'VOID_MOTION_RESOLVED_FROM_EVENT',v_motion_resolution_old,v_motion_resolution_new,v_case_id,'Motion Resolved voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_court_filings' OR v_event_type_code = 'COURT_FILING' THEN
    SELECT cf.id, to_jsonb(cf) INTO v_filing_id, v_filing_old FROM public.case_court_filings cf WHERE cf.id = v_source_id OR cf.case_event_id = p_case_event_id ORDER BY CASE WHEN cf.id = v_source_id THEN 0 ELSE 1 END LIMIT 1;
    IF v_filing_id IS NOT NULL THEN
      UPDATE public.case_court_filings SET is_voided = true, voided_at = now(), voided_by_user_id = p_voided_by_user_id, void_reason = p_void_reason, updated_by_user_id = p_voided_by_user_id, updated_at = now() WHERE id = v_filing_id;
      SELECT to_jsonb(cf) INTO v_filing_new FROM public.case_court_filings cf WHERE cf.id = v_filing_id;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      SELECT to_jsonb(cpd) INTO v_new_details
      FROM public.case_private_details cpd
      WHERE cpd.case_id = v_case_id;

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_court_filings',v_filing_id,'VOID_COURT_FILING_FROM_EVENT',v_filing_old,jsonb_build_object('court_filing',v_filing_new,'case_private_details',v_new_details),v_case_id,'Court filing voided and case status recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF v_event_type_code = 'CASE_ASSIGNMENT' THEN
    SELECT ca.id, to_jsonb(ca) INTO v_assignment_id, v_assignment_old
    FROM public.case_assignments ca
    WHERE ca.id = v_source_id OR ca.case_event_id = p_case_event_id
    ORDER BY CASE WHEN ca.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_assignment_id IS NOT NULL THEN
      UPDATE public.case_assignments
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          unassigned_at = COALESCE(unassigned_at, now())
      WHERE id = v_assignment_id;

      SELECT to_jsonb(ca) INTO v_assignment_new
      FROM public.case_assignments ca
      WHERE ca.id = v_assignment_id;

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (
        p_voided_by_user_id,
        'case_assignments',
        v_assignment_id,
        'VOID_CASE_ASSIGNMENT_FROM_EVENT',
        v_assignment_old,
        v_assignment_new,
        v_case_id,
        'Assignment row voided because the Case Assignment event was voided.',
        jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason)
      );
    END IF;
  ELSIF v_event_type_code = 'CASE_REASSIGNMENT' THEN
    v_previous_assignment_id := NULLIF(v_old#>>'{details_jsonb,previous_assignment_id}', '')::bigint;

    SELECT ca.id, to_jsonb(ca) INTO v_assignment_id, v_assignment_old
    FROM public.case_assignments ca
    WHERE ca.id = v_source_id OR ca.case_event_id = p_case_event_id
    ORDER BY CASE WHEN ca.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    SELECT ca.id INTO v_latest_assignment_id
    FROM public.case_assignments ca
    WHERE ca.case_id = v_case_id
      AND ca.is_voided IS FALSE
    ORDER BY ca.assigned_at DESC NULLS LAST, ca.id DESC
    LIMIT 1;

    IF v_assignment_id IS NULL OR v_latest_assignment_id IS DISTINCT FROM v_assignment_id THEN
      RAISE EXCEPTION 'This reassignment has already been superseded by a later assignment. Void the latest reassignment first.';
    END IF;

    UPDATE public.case_assignments
    SET is_voided = true,
        voided_at = now(),
        voided_by_user_id = p_voided_by_user_id,
        void_reason = p_void_reason,
        unassigned_at = COALESCE(unassigned_at, now())
    WHERE id = v_assignment_id;

    SELECT to_jsonb(ca) INTO v_assignment_new
    FROM public.case_assignments ca
    WHERE ca.id = v_assignment_id;

    IF v_previous_assignment_id IS NOT NULL THEN
      SELECT to_jsonb(ca) INTO v_previous_assignment_old
      FROM public.case_assignments ca
      WHERE ca.id = v_previous_assignment_id
        AND ca.case_id = v_case_id
      FOR UPDATE;

      IF v_previous_assignment_old IS NOT NULL THEN
        UPDATE public.case_assignments
        SET unassigned_at = NULL,
            unassigned_by_user_id = NULL,
            unassignment_reason = NULL
        WHERE id = v_previous_assignment_id
          AND case_id = v_case_id
          AND is_voided IS FALSE;

        SELECT to_jsonb(ca) INTO v_previous_assignment_new
        FROM public.case_assignments ca
        WHERE ca.id = v_previous_assignment_id;
      END IF;
    END IF;

    INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
    VALUES (
      p_voided_by_user_id,
      'case_assignments',
      v_assignment_id,
      'VOID_CASE_REASSIGNMENT_NEW_ASSIGNMENT',
      v_assignment_old,
      v_assignment_new,
      v_case_id,
      'Reassignment-created assignment row voided because the Case Reassignment event was voided.',
      jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason,'previous_assignment_id',v_previous_assignment_id)
    );

    IF v_previous_assignment_old IS NOT NULL THEN
      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (
        p_voided_by_user_id,
        'case_assignments',
        v_previous_assignment_id,
        'RESTORE_PREVIOUS_ASSIGNMENT_FROM_REASSIGNMENT_VOID',
        v_previous_assignment_old,
        v_previous_assignment_new,
        v_case_id,
        'Previous assignment restored because the Case Reassignment event was voided.',
        jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason,'voided_assignment_id',v_assignment_id)
      );
    END IF;
  ELSIF lower(coalesce(v_source_table,'')) = 'case_assignments' THEN
    UPDATE public.case_assignments
    SET is_voided = true,
        voided_at = now(),
        voided_by_user_id = p_voided_by_user_id,
        void_reason = p_void_reason,
        unassigned_at = COALESCE(unassigned_at, now())
    WHERE id = v_source_id OR case_event_id = p_case_event_id;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_resolutions' OR v_event_type_code = 'CASE_RESOLVED' THEN
    SELECT cr.id INTO v_resolution_id FROM public.case_resolutions cr WHERE cr.id = v_source_id OR cr.case_event_id = p_case_event_id LIMIT 1;
    IF v_resolution_id IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.case_resolution_approvals a WHERE a.case_resolution_id = v_resolution_id AND a.is_voided = false) THEN
        RAISE EXCEPTION 'This resolution already has approved decisions. Void the approval events first.';
      END IF;
      UPDATE public.case_resolutions SET is_voided=true, voided_at=now(), voided_by_user_id=p_voided_by_user_id, void_reason=p_void_reason, updated_by_user_id=p_voided_by_user_id, updated_at=now() WHERE id=v_resolution_id;
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_resolution_approvals' OR v_event_type_code = 'CASE_DECISION_APPROVED' THEN
    SELECT a.id INTO v_approval_id FROM public.case_resolution_approvals a WHERE a.id = v_source_id OR a.case_event_id = p_case_event_id LIMIT 1;
    IF v_approval_id IS NOT NULL THEN
      UPDATE public.case_resolution_approvals SET is_voided=true, voided_at=now(), voided_by_user_id=p_voided_by_user_id, void_reason=p_void_reason, updated_by_user_id=p_voided_by_user_id, updated_at=now() WHERE id=v_approval_id;
    END IF;
  END IF;

  IF v_event_type_code IN ('CASE_RESOLVED','CASE_DECISION_APPROVED','CASE_ASSIGNMENT','CASE_REASSIGNMENT')
     OR lower(coalesce(v_source_table,'')) IN ('case_resolutions','case_resolution_approvals','case_assignments') THEN
    PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

    IF v_event_type_code = 'CASE_REASSIGNMENT' THEN
      SELECT to_jsonb(cpd) INTO v_new_details
      FROM public.case_private_details cpd
      WHERE cpd.case_id = v_case_id;

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (
        p_voided_by_user_id,
        'case_private_details',
        v_case_id,
        'CASE_REASSIGNMENT_VOID_STATUS_STAGE_RECOMPUTED',
        v_old_details,
        v_new_details,
        v_case_id,
        'Case Reassignment voided; case status and case stage recomputed from active workflow records.',
        jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason,'restored_assignment_id',v_previous_assignment_id,'voided_assignment_id',v_assignment_id)
      );
    END IF;
  END IF;

END;
$$;

GRANT EXECUTE ON FUNCTION public.void_case_event(bigint, text, bigint) TO authenticated;

-- Verification: record -> PENDING/PENDING_PETREV; filed_by check rejects invalid values; details order is preserved; updates insert no case_events row; only latest update can be voided; audit logs are written; unrelated workflows are not changed by the dedicated update RPC.

COMMIT;
