BEGIN;

INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
VALUES ('CASE_STATUS_UPDATED', 'Case Status Updated', 'STATUS', 'Manual state-changing Case Status / Case Stage timeline event.', 172, false, true)
ON CONFLICT (code) DO UPDATE SET display_label=EXCLUDED.display_label, category=EXCLUDED.category, description=EXCLUDED.description, sort_order=EXCLUDED.sort_order, is_active=true, updated_at=now();

CREATE TABLE IF NOT EXISTS public.case_manual_status_updates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  case_event_id bigint REFERENCES public.case_events(id) ON DELETE SET NULL,
  selected_case_status_id bigint NOT NULL REFERENCES public.case_statuses(id),
  selected_case_stage_id bigint NOT NULL REFERENCES public.case_stages(id),
  status_date date NOT NULL,
  remarks text,
  reason text NOT NULL,
  created_by_user_id bigint REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_voided boolean NOT NULL DEFAULT false,
  voided_at timestamptz,
  voided_by_user_id bigint REFERENCES public.users(id),
  void_reason text
);
CREATE INDEX IF NOT EXISTS idx_case_manual_status_updates_case_active ON public.case_manual_status_updates(case_id, is_voided, status_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_case_manual_status_updates_event ON public.case_manual_status_updates(case_event_id);
GRANT ALL ON TABLE public.case_manual_status_updates TO authenticated, service_role;
GRANT ALL ON SEQUENCE public.case_manual_status_updates_id_seq TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.add_case_stage(p_display_label text, p_code text DEFAULT NULL, p_user_id bigint DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_label text := nullif(btrim(p_display_label), '');
  v_code text := nullif(upper(regexp_replace(btrim(coalesce(p_code, p_display_label)), '[^A-Za-z0-9]+', '_', 'g')), '');
  v_id bigint;
  v_new jsonb;
BEGIN
  IF v_label IS NULL THEN RAISE EXCEPTION 'Display Label is required'; END IF;
  v_code := regexp_replace(v_code, '^_+|_+$', '', 'g');
  IF v_code IS NULL OR v_code = '' THEN RAISE EXCEPTION 'Case Stage code is required'; END IF;
  IF EXISTS (SELECT 1 FROM public.case_stages WHERE upper(code) = v_code) THEN RAISE EXCEPTION 'Case Stage code already exists'; END IF;
  IF EXISTS (SELECT 1 FROM public.case_stages WHERE is_active IS TRUE AND lower(regexp_replace(btrim(display_label::text), '\s+', ' ', 'g')) = lower(regexp_replace(v_label, '\s+', ' ', 'g'))) THEN RAISE EXCEPTION 'An active Case Stage with this label already exists'; END IF;

  INSERT INTO public.case_stages(code, display_label, sort_order, is_final_stage, is_milestone, is_active)
  VALUES (v_code, v_label, COALESCE((SELECT max(sort_order) + 10 FROM public.case_stages), 10), false, false, true)
  RETURNING id INTO v_id;

  SELECT to_jsonb(cs) INTO v_new FROM public.case_stages cs WHERE cs.id = v_id;
  INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,new_data,summary,metadata)
  VALUES (p_user_id,'case_stages',v_id,'ADD_CASE_STAGE',v_new,'Added Case Stage ' || v_label || '.',jsonb_build_object('code',v_code));
  RETURN v_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.add_case_stage(text,text,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.compute_current_case_state(p_case_id bigint)
RETURNS TABLE(case_status_code text, case_stage_code text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_active_petition_count integer; v_petition_status_code text; v_petition_stage_code text;
  v_motion_resolution_for_approval_count integer; v_pending_motion_count integer; v_unapproved_resolution_count integer; v_unfiled_for_filing_count integer; v_filed_for_filing_count integer; v_dismissal_count integer; v_active_assignment_count integer; v_explicit_status_code text; v_explicit_stage_code text;
BEGIN
  SELECT count(*) INTO v_active_petition_count
  FROM public.case_petitions_for_review p
  JOIN public.case_events ce ON ce.id=p.case_event_id AND ce.is_voided=false
  WHERE p.case_id=p_case_id AND p.is_voided=false;

  SELECT cs.code, cst.code INTO v_petition_status_code, v_petition_stage_code
  FROM public.case_petition_for_review_updates u
  JOIN public.case_petitions_for_review p ON p.id=u.petition_for_review_id AND p.is_voided=false
  JOIN public.case_events pe ON pe.id=p.case_event_id AND pe.is_voided=false
  JOIN public.case_statuses cs ON cs.id=u.selected_case_status_id AND cs.is_active IS TRUE
  JOIN public.case_stages cst ON cst.id=u.selected_case_stage_id AND cst.is_active IS TRUE
  WHERE u.case_id=p_case_id AND u.is_voided=false AND u.updates_case_status=true
  ORDER BY u.status_date DESC, NULL::time without time zone DESC NULLS LAST, pe.id DESC, u.id DESC
  LIMIT 1;

  SELECT count(*) INTO v_motion_resolution_for_approval_count FROM public.case_motion_resolutions cmr JOIN public.case_motions cm ON cm.id=cmr.case_motion_id AND cm.is_voided=false JOIN public.case_events re ON re.id=cmr.case_event_id AND re.is_voided=false JOIN public.case_events me ON me.id=cm.case_event_id AND me.is_voided=false WHERE cmr.case_id=p_case_id AND cmr.is_voided=false AND NOT EXISTS (SELECT 1 FROM public.case_motion_resolution_approvals a JOIN public.case_events ae ON ae.id=a.case_event_id AND ae.is_voided=false WHERE a.case_motion_resolution_id=cmr.id AND a.is_voided=false);
  SELECT count(*) INTO v_pending_motion_count FROM public.case_motions cm JOIN public.case_events ce ON ce.id=cm.case_event_id AND ce.is_voided=false WHERE cm.case_id=p_case_id AND cm.is_voided=false AND cm.case_event_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.case_motion_resolutions cmr WHERE cmr.case_motion_id=cm.id AND cmr.is_voided=false);
  IF COALESCE(v_motion_resolution_for_approval_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'MOTION_RESO_FOR_APPROVAL'::text; RETURN; ELSIF COALESCE(v_pending_motion_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'MOTION_PENDING'::text; RETURN; END IF;

  SELECT count(*) INTO v_unapproved_resolution_count FROM public.case_resolutions cr WHERE cr.case_id=p_case_id AND cr.is_voided=false AND NOT EXISTS (SELECT 1 FROM public.case_resolution_approvals a WHERE a.case_resolution_id=cr.id AND a.is_voided=false);
  SELECT count(*) FILTER (WHERE aa.decision_code='FOR_FILING' AND EXISTS (SELECT 1 FROM public.case_court_filings cf WHERE cf.case_resolution_approval_action_id=aa.id AND cf.is_voided=false)), count(*) FILTER (WHERE aa.decision_code='FOR_FILING' AND NOT EXISTS (SELECT 1 FROM public.case_court_filings cf WHERE cf.case_resolution_approval_action_id=aa.id AND cf.is_voided=false)), count(*) FILTER (WHERE aa.decision_code='DISMISSAL') INTO v_filed_for_filing_count, v_unfiled_for_filing_count, v_dismissal_count FROM public.case_resolution_approval_actions aa JOIN public.case_resolution_approvals a ON a.id=aa.approval_id AND a.is_voided=false JOIN public.case_resolutions cr ON cr.id=a.case_resolution_id AND cr.is_voided=false WHERE aa.case_id=p_case_id;
  IF COALESCE(v_unapproved_resolution_count,0)>0 THEN IF COALESCE(v_filed_for_filing_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'FILED_OTHER_RESO_FOR_APPROVAL'::text; ELSE RETURN QUERY SELECT 'PENDING'::text,'RESO_FOR_APPROVAL'::text; END IF; RETURN; ELSIF COALESCE(v_unfiled_for_filing_count,0)>0 THEN IF COALESCE(v_filed_for_filing_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'FILED_OTHER_INFO_FOR_FILING'::text; ELSE RETURN QUERY SELECT 'PENDING'::text,'FOR_FILING'::text; END IF; RETURN; END IF;

  IF COALESCE(v_active_petition_count,0) > 0 AND v_petition_status_code IS NULL THEN RETURN QUERY SELECT 'PENDING'::text, 'PENDING_PETREV'::text; RETURN; END IF;

  SELECT explicit_state.status_code, explicit_state.stage_code INTO v_explicit_status_code, v_explicit_stage_code
  FROM (
    SELECT cs.code AS status_code, cst.code AS stage_code, ce.event_date, ce.event_time, ce.id AS case_event_id, msu.id AS source_id
    FROM public.case_manual_status_updates msu
    JOIN public.case_events ce ON ce.id=msu.case_event_id AND ce.is_voided=false
    JOIN public.case_event_types cet ON cet.id=ce.event_type_id AND cet.code='CASE_STATUS_UPDATED'
    JOIN public.case_statuses cs ON cs.id=msu.selected_case_status_id AND cs.is_active IS TRUE
    JOIN public.case_stages cst ON cst.id=msu.selected_case_stage_id AND cst.is_active IS TRUE
    WHERE msu.case_id=p_case_id AND msu.is_voided=false AND (COALESCE(v_active_petition_count,0)=0 OR v_petition_status_code IS NOT NULL)
    UNION ALL
    SELECT cs.code, cst.code, ce.event_date, ce.event_time, ce.id, a.id
    FROM public.case_motion_resolution_approvals a
    JOIN public.case_events ce ON ce.id=a.case_event_id AND ce.is_voided=false
    JOIN public.case_statuses cs ON cs.id=a.selected_case_status_id AND cs.is_active IS TRUE
    JOIN public.case_stages cst ON cst.id=a.selected_case_stage_id AND cst.is_active IS TRUE
    JOIN public.case_motion_resolutions r ON r.id=a.case_motion_resolution_id AND r.is_voided=false
    JOIN public.case_motions m ON m.id=a.case_motion_id AND m.is_voided=false
    WHERE a.case_id=p_case_id AND a.is_voided=false AND a.updates_case_status=true
    UNION ALL
    SELECT cs.code, cst.code, u.status_date, NULL::time without time zone, pe.id, u.id
    FROM public.case_petition_for_review_updates u
    JOIN public.case_petitions_for_review p ON p.id=u.petition_for_review_id AND p.is_voided=false
    JOIN public.case_events pe ON pe.id=p.case_event_id AND pe.is_voided=false
    JOIN public.case_statuses cs ON cs.id=u.selected_case_status_id AND cs.is_active IS TRUE
    JOIN public.case_stages cst ON cst.id=u.selected_case_stage_id AND cst.is_active IS TRUE
    WHERE u.case_id=p_case_id AND u.is_voided=false AND u.updates_case_status=true
  ) explicit_state
  ORDER BY explicit_state.event_date DESC, explicit_state.event_time DESC NULLS LAST, explicit_state.case_event_id DESC, explicit_state.source_id DESC
  LIMIT 1;
  IF v_explicit_status_code IS NOT NULL THEN RETURN QUERY SELECT v_explicit_status_code, v_explicit_stage_code; RETURN; END IF;

  SELECT count(*) INTO v_active_assignment_count FROM public.case_assignments ca WHERE ca.case_id=p_case_id AND ca.unassigned_at IS NULL AND ca.is_voided IS FALSE;
  IF COALESCE(v_filed_for_filing_count,0)>0 AND COALESCE(v_dismissal_count,0)>0 THEN RETURN QUERY SELECT 'MIXED_RESULT'::text,'MIXED_RESULT'::text; ELSIF COALESCE(v_filed_for_filing_count,0)>0 THEN RETURN QUERY SELECT 'FILED'::text,'FILED'::text; ELSIF COALESCE(v_dismissal_count,0)>0 THEN RETURN QUERY SELECT 'DISMISSED'::text,'DISMISSED'::text; ELSIF COALESCE(v_active_assignment_count,0)>0 THEN RETURN QUERY SELECT 'PENDING'::text,'CASE_RAFFLED'::text; ELSE RETURN QUERY SELECT 'PENDING'::text,'FOR_RAFFLE'::text; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_case_status_updated_event(p_case_id bigint,p_case_status_id bigint,p_case_stage_id bigint,p_status_date date,p_remarks text DEFAULT NULL,p_reason text DEFAULT NULL,p_user_id bigint DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  v_event_type_id bigint; v_event_id bigint; v_update_id bigint; v_status_code text; v_status_label text; v_stage_code text; v_stage_label text; v_prev_status_id bigint; v_prev_stage_id bigint; v_prev_status_label text; v_prev_stage_label text; v_status_history_id bigint; v_stage_history_id bigint; v_old jsonb; v_new jsonb; v_remarks text:=nullif(btrim(coalesce(p_remarks,'')), ''); v_reason text:=nullif(btrim(coalesce(p_reason,'')), ''); v_time time;
BEGIN
  IF p_case_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.cases WHERE id=p_case_id) THEN RAISE EXCEPTION 'Case % not found', p_case_id; END IF;
  IF p_status_date IS NULL THEN RAISE EXCEPTION 'Status Date is required'; END IF;
  IF v_reason IS NULL THEN RAISE EXCEPTION 'Reason for Edit is required'; END IF;
  SELECT code, display_label INTO v_status_code, v_status_label FROM public.case_statuses WHERE id=p_case_status_id AND is_active IS TRUE;
  IF v_status_code IS NULL THEN RAISE EXCEPTION 'Selected Case Status must be active'; END IF;
  IF v_status_code NOT IN ('PENDING','FILED','DISMISSED','MIXED_RESULT') THEN RAISE EXCEPTION 'Selected Case Status must be PENDING, FILED, DISMISSED, or MIXED_RESULT'; END IF;
  SELECT code, display_label INTO v_stage_code, v_stage_label FROM public.case_stages WHERE id=p_case_stage_id AND is_active IS TRUE;
  IF v_stage_code IS NULL THEN RAISE EXCEPTION 'Selected Case Stage must be active'; END IF;
  SELECT id INTO v_event_type_id FROM public.case_event_types WHERE code='CASE_STATUS_UPDATED' AND is_active IS TRUE LIMIT 1;
  IF v_event_type_id IS NULL THEN RAISE EXCEPTION 'Missing CASE_STATUS_UPDATED event type'; END IF;
  INSERT INTO public.case_private_details(case_id, source) VALUES (p_case_id, 'MANUAL_ENTRY') ON CONFLICT (case_id) DO NOTHING;
  SELECT current_case_status_id, current_case_stage_id, to_jsonb(cpd) INTO v_prev_status_id, v_prev_stage_id, v_old FROM public.case_private_details cpd WHERE cpd.case_id=p_case_id;
  v_prev_status_id := COALESCE(v_prev_status_id, (SELECT current_status_id FROM public.case_private_details WHERE case_id=p_case_id));
  SELECT display_label INTO v_prev_status_label FROM public.case_statuses WHERE id=v_prev_status_id;
  SELECT display_label INTO v_prev_stage_label FROM public.case_stages WHERE id=v_prev_stage_id;
  v_time := (now() AT TIME ZONE 'Asia/Manila')::time(0);

  INSERT INTO public.case_events(case_id,event_type_id,event_date,event_time,title,description,status_id,case_status_id,case_stage_id,details_jsonb,source,source_table,created_by_user_id,updated_by_user_id)
  VALUES (p_case_id,v_event_type_id,p_status_date,v_time,'Case Status Updated',COALESCE(v_remarks,v_reason),p_case_status_id,p_case_status_id,p_case_stage_id,jsonb_build_object('selected_case_status_id',p_case_status_id,'selected_case_status_code',v_status_code,'selected_case_status_label',v_status_label,'selected_case_stage_id',p_case_stage_id,'selected_case_stage_code',v_stage_code,'selected_case_stage_label',v_stage_label,'status_date',p_status_date,'remarks',v_remarks,'reason',v_reason,'previous_case_status_id',v_prev_status_id,'previous_case_status_label',v_prev_status_label,'previous_case_stage_id',v_prev_stage_id,'previous_case_stage_label',v_prev_stage_label),'MANUAL_ENTRY','case_manual_status_updates',p_user_id,p_user_id)
  RETURNING id INTO v_event_id;

  INSERT INTO public.case_manual_status_updates(case_id,case_event_id,selected_case_status_id,selected_case_stage_id,status_date,remarks,reason,created_by_user_id)
  VALUES (p_case_id,v_event_id,p_case_status_id,p_case_stage_id,p_status_date,v_remarks,v_reason,p_user_id)
  RETURNING id INTO v_update_id;
  UPDATE public.case_events SET source_id=v_update_id WHERE id=v_event_id;

  UPDATE public.case_private_details SET current_status_id=p_case_status_id,current_status_date=p_status_date,current_status_remarks=COALESCE(v_remarks,v_reason),current_case_status_id=p_case_status_id,current_case_status_date=p_status_date,current_case_status_remarks=COALESCE(v_remarks,v_reason),current_case_stage_id=p_case_stage_id,current_case_stage_date=p_status_date,current_case_stage_remarks=COALESCE(v_remarks,v_reason),updated_at=now() WHERE case_id=p_case_id;
  UPDATE public.cases SET updated_by_user_id=p_user_id, updated_at=now() WHERE id=p_case_id;
  IF v_prev_status_id IS DISTINCT FROM p_case_status_id THEN INSERT INTO public.case_status_history(case_id,from_status_id,to_status_id,changed_by_user_id,changed_at,status_date,remarks,case_event_id) VALUES(p_case_id,v_prev_status_id,p_case_status_id,p_user_id,now(),p_status_date,COALESCE(v_remarks,v_reason),v_event_id) RETURNING id INTO v_status_history_id; END IF;
  IF v_prev_stage_id IS DISTINCT FROM p_case_stage_id THEN INSERT INTO public.case_stage_history(case_id,from_stage_id,to_stage_id,changed_by_user_id,changed_at,stage_date,remarks,case_event_id) VALUES(p_case_id,v_prev_stage_id,p_case_stage_id,p_user_id,now(),p_status_date,COALESCE(v_remarks,v_reason),v_event_id) RETURNING id INTO v_stage_history_id; END IF;
  SELECT to_jsonb(cpd) INTO v_new FROM public.case_private_details cpd WHERE cpd.case_id=p_case_id;
  INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata) VALUES(p_user_id,'case_manual_status_updates',v_update_id,'CASE_STATUS_UPDATED',v_old,v_new,p_case_id,'Case Status Updated recorded.',jsonb_build_object('case_event_id',v_event_id,'status_history_id',v_status_history_id,'case_stage_history_id',v_stage_history_id,'selected_case_status_code',v_status_code,'selected_case_stage_code',v_stage_code));
  RETURN v_event_id;
END; $$;
GRANT EXECUTE ON FUNCTION public.record_case_status_updated_event(bigint,bigint,bigint,date,text,text,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.edit_case_overview_section(p_payload jsonb)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_case_id bigint := (p_payload->>'caseId')::bigint;
  v_section text := lower(btrim(p_payload->>'section'));
  v_reason text := nullif(btrim(p_payload->>'reason'), '');
  v_user_id bigint := nullif(p_payload->>'userId','')::bigint;
  v_old jsonb;
  v_new jsonb;
  v_event_type_id bigint;
  v_event_id bigint;
  v_old_date_received date;
  v_new_date_received date;
  v_case_received_sync text;
BEGIN
  IF v_section = 'status' THEN
    RETURN public.record_case_status_updated_event(v_case_id, nullif(p_payload#>>'{data,statusId}','')::bigint, nullif(p_payload#>>'{data,stageId}','')::bigint, nullif(p_payload#>>'{data,statusDate}','')::date, nullif(btrim(p_payload#>>'{data,remarks}'),''), v_reason, v_user_id);
  END IF;
  IF v_case_id IS NULL THEN RAISE EXCEPTION 'caseId is required'; END IF;
  IF v_section IS NULL THEN RAISE EXCEPTION 'section is required'; END IF;
  IF v_reason IS NULL THEN RAISE EXCEPTION 'reason is required'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.cases WHERE id = v_case_id) THEN RAISE EXCEPTION 'Case % not found', v_case_id; END IF;
  SELECT jsonb_build_object('cases', to_jsonb(c), 'case_private_details', to_jsonb(cpd)) INTO v_old FROM public.cases c LEFT JOIN public.case_private_details cpd ON cpd.case_id = c.id WHERE c.id = v_case_id;
  IF v_section = 'docket_info' THEN
    SELECT date_received INTO v_old_date_received FROM public.cases WHERE id = v_case_id;
    UPDATE public.cases SET docket_type_id = COALESCE(nullif(p_payload#>>'{data,docketTypeId}','')::bigint, docket_type_id), docket_year = COALESCE(nullif(p_payload#>>'{data,docketYear}','')::int, docket_year), docket_number = COALESCE(nullif(p_payload#>>'{data,docketNumber}','')::int, docket_number), docket_month_code = COALESCE(nullif(btrim(p_payload#>>'{data,docketMonthCode}'),''), docket_month_code), date_received = COALESCE(nullif(p_payload#>>'{data,dateReceived}','')::date, date_received), updated_by_user_id = v_user_id, updated_at = now() WHERE id = v_case_id;
    SELECT date_received INTO v_new_date_received FROM public.cases WHERE id = v_case_id;
    IF v_new_date_received IS DISTINCT FROM v_old_date_received THEN
      SELECT id INTO v_event_type_id FROM public.case_event_types WHERE code = 'CASE_RECEIVED' AND is_active IS TRUE LIMIT 1;
      IF v_event_type_id IS NULL THEN v_case_received_sync := 'skipped_missing_event_type'; ELSE
        SELECT id INTO v_event_id FROM public.case_events WHERE case_id = v_case_id AND event_type_id = v_event_type_id AND COALESCE(is_voided, false) IS FALSE ORDER BY event_date DESC NULLS LAST, id DESC LIMIT 1;
        IF v_event_id IS NOT NULL THEN UPDATE public.case_events SET event_date = v_new_date_received, title = COALESCE(NULLIF(title, ''), 'Case received'), description = COALESCE(NULLIF(description, ''), 'Case received date updated from overview edit'), details_jsonb = COALESCE(details_jsonb, '{}'::jsonb) || jsonb_build_object('action', 'sync_case_received_from_overview', 'old_date_received', v_old_date_received, 'new_date_received', v_new_date_received, 'reason', v_reason), updated_by_user_id = v_user_id, updated_at = now() WHERE id = v_event_id; v_case_received_sync := 'updated_existing_event';
        ELSIF v_new_date_received IS NOT NULL THEN INSERT INTO public.case_events(case_id,event_type_id,event_date,title,description,details_jsonb,source,source_table,source_id,created_by_user_id,updated_by_user_id) VALUES (v_case_id,v_event_type_id,v_new_date_received,'Case received','Case received date updated from overview edit',jsonb_build_object('action', 'sync_case_received_from_overview', 'old_date_received', v_old_date_received, 'new_date_received', v_new_date_received, 'reason', v_reason),'MANUAL_EDIT','cases',v_case_id,v_user_id,v_user_id); v_case_received_sync := 'created_missing_event';
        ELSE v_case_received_sync := 'skipped_null_date_received'; END IF;
      END IF;
    END IF;
  ELSIF v_section = 'case_details' THEN
    UPDATE public.cases SET case_classification_id = nullif(p_payload#>>'{data,caseClassificationId}','')::bigint, updated_by_user_id = v_user_id, updated_at = now() WHERE id = v_case_id;
    INSERT INTO public.case_private_details(case_id, source) VALUES (v_case_id, 'MANUAL_ENTRY') ON CONFLICT (case_id) DO NOTHING;
    UPDATE public.case_private_details SET is_summary_procedure = COALESCE(nullif(p_payload#>>'{data,isSummaryProcedure}','')::boolean, false), summary_text = nullif(btrim(p_payload#>>'{data,summaryText}'),''), remarks = nullif(btrim(p_payload#>>'{data,remarks}'),'') WHERE case_id = v_case_id;
  ELSE
    RAISE EXCEPTION 'Editing section % is not implemented yet', v_section;
  END IF;
  SELECT jsonb_build_object('cases', to_jsonb(c), 'case_private_details', to_jsonb(cpd)) INTO v_new FROM public.cases c LEFT JOIN public.case_private_details cpd ON cpd.case_id = c.id WHERE c.id = v_case_id;
  INSERT INTO public.audit_logs(actor_user_id, action, entity_name, entity_id, case_id, summary, metadata, old_data, new_data) VALUES (v_user_id, 'EDIT_CASE_OVERVIEW_' || upper(v_section), 'cases', v_case_id, v_case_id, 'Edited case overview ' || replace(v_section, '_', ' '), jsonb_strip_nulls(jsonb_build_object('reason', v_reason, 'section', v_section, 'case_received_event_sync', v_case_received_sync)), v_old, v_new);
  RETURN v_case_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.edit_case_overview_section(jsonb) TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.void_case_event(p_case_event_id bigint, p_void_reason text, p_voided_by_user_id bigint DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_old jsonb; v_new jsonb; v_case_id bigint; v_event_type_code text; v_source_table text; v_source_id bigint;
  v_filing_id bigint; v_filing_old jsonb; v_filing_new jsonb; v_approval_id bigint; v_resolution_id bigint;
  v_assignment_id bigint; v_assignment_old jsonb; v_assignment_new jsonb;
  v_motion_id bigint; v_motion_old jsonb; v_motion_new jsonb;
  v_petition_id bigint; v_petition_old jsonb; v_petition_new jsonb;
  v_manual_update_id bigint; v_manual_update_old jsonb; v_manual_update_new jsonb;
  v_motion_resolution_id bigint; v_motion_resolution_old jsonb; v_motion_resolution_new jsonb; v_motion_approval_count integer;
  v_motion_decision_approval_id bigint; v_motion_decision_approval_old jsonb; v_motion_decision_approval_new jsonb;
  v_previous_assignment_id bigint; v_previous_assignment_old jsonb; v_previous_assignment_new jsonb; v_latest_assignment_id bigint;
  v_status_code text; v_status_label text; v_status_id bigint; v_prev_status_id bigint; v_status_history_id bigint; v_old_details jsonb; v_new_details jsonb;
BEGIN
  IF nullif(trim(p_void_reason), '') IS NULL THEN RAISE EXCEPTION 'Void reason is required'; END IF;
  SELECT to_jsonb(ce), ce.case_id, cet.code, ce.source_table, ce.source_id INTO v_old, v_case_id, v_event_type_code, v_source_table, v_source_id
  FROM public.case_events ce LEFT JOIN public.case_event_types cet ON cet.id = ce.event_type_id WHERE ce.id = p_case_event_id AND ce.is_voided = false;
  IF v_old IS NULL THEN RAISE EXCEPTION 'Active case event % not found', p_case_event_id; END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_resolution_approvals' OR v_event_type_code = 'CASE_DECISION_APPROVED' THEN
    SELECT a.id INTO v_approval_id FROM public.case_resolution_approvals a WHERE a.id = v_source_id OR a.case_event_id = p_case_event_id LIMIT 1;
    IF v_approval_id IS NOT NULL AND EXISTS (SELECT 1 FROM public.case_court_filings cf JOIN public.case_resolution_approval_actions aa ON aa.id = cf.case_resolution_approval_action_id WHERE aa.approval_id = v_approval_id AND cf.is_voided = false) THEN
      RAISE EXCEPTION 'This approval has a court filing. Void the court filing first.';
    END IF;
  END IF;
  IF lower(coalesce(v_source_table,'')) = 'case_resolutions' OR v_event_type_code = 'CASE_RESOLVED' THEN
    SELECT cr.id INTO v_resolution_id FROM public.case_resolutions cr WHERE cr.id = v_source_id OR cr.case_event_id = p_case_event_id LIMIT 1;
    IF v_resolution_id IS NOT NULL AND EXISTS (SELECT 1 FROM public.case_court_filings cf JOIN public.case_resolution_approval_actions aa ON aa.id = cf.case_resolution_approval_action_id JOIN public.case_resolution_approvals a ON a.id = aa.approval_id WHERE a.case_resolution_id = v_resolution_id AND cf.is_voided = false) THEN
      RAISE EXCEPTION 'This resolution has a court filing. Void the court filing first.';
    END IF;
  END IF;

  SELECT current_status_id, to_jsonb(cpd) INTO v_prev_status_id, v_old_details FROM public.case_private_details cpd WHERE cpd.case_id = v_case_id;
  UPDATE public.case_events SET is_voided = true, void_reason = p_void_reason, voided_at = now(), voided_by_user_id = p_voided_by_user_id, updated_by_user_id = p_voided_by_user_id, updated_at = now() WHERE id = p_case_event_id;
  SELECT to_jsonb(ce) INTO v_new FROM public.case_events ce WHERE ce.id = p_case_event_id;
  INSERT INTO public.audit_logs(actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata) VALUES (p_voided_by_user_id, 'case_events', p_case_event_id, 'VOID_CASE_EVENT', v_old, v_new, v_case_id, 'Voided case timeline activity', jsonb_build_object('reason', p_void_reason));

  IF lower(coalesce(v_source_table,'')) = 'case_petitions_for_review' OR v_event_type_code = 'PETITION_FOR_REVIEW' THEN
    SELECT p.id, to_jsonb(p) INTO v_petition_id, v_petition_old
    FROM public.case_petitions_for_review p
    WHERE p.id = v_source_id OR p.case_event_id = p_case_event_id
    ORDER BY CASE WHEN p.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;
    IF v_petition_id IS NOT NULL THEN
      UPDATE public.case_petitions_for_review
      SET is_voided = true, voided_at = now(), voided_by_user_id = p_voided_by_user_id, void_reason = p_void_reason, updated_by_user_id = p_voided_by_user_id, updated_at = now()
      WHERE id = v_petition_id;
      SELECT to_jsonb(p) INTO v_petition_new FROM public.case_petitions_for_review p WHERE p.id = v_petition_id;
      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);
      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_petitions_for_review',v_petition_id,'VOID_PETITION_FOR_REVIEW_FROM_EVENT',v_petition_old,v_petition_new,v_case_id,'Petition for Review voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_manual_status_updates' OR v_event_type_code = 'CASE_STATUS_UPDATED' THEN
    SELECT msu.id, to_jsonb(msu) INTO v_manual_update_id, v_manual_update_old
    FROM public.case_manual_status_updates msu
    WHERE msu.id = v_source_id OR msu.case_event_id = p_case_event_id
    ORDER BY CASE WHEN msu.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;
    IF v_manual_update_id IS NOT NULL THEN
      UPDATE public.case_manual_status_updates
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_at = now()
      WHERE id = v_manual_update_id;
      SELECT to_jsonb(msu) INTO v_manual_update_new FROM public.case_manual_status_updates msu WHERE msu.id = v_manual_update_id;
      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);
      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_manual_status_updates',v_manual_update_id,'VOID_CASE_STATUS_UPDATED_FROM_EVENT',v_manual_update_old,v_manual_update_new,v_case_id,'Manual Case Status Updated event voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_motions' OR v_event_type_code = 'MOTION_RECEIVED' THEN
    SELECT cm.id, to_jsonb(cm) INTO v_motion_id, v_motion_old FROM public.case_motions cm WHERE cm.id = v_source_id OR cm.case_event_id = p_case_event_id ORDER BY CASE WHEN cm.id = v_source_id THEN 0 ELSE 1 END LIMIT 1;
    IF v_motion_id IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.case_motion_resolutions cmr WHERE cmr.case_motion_id = v_motion_id AND cmr.is_voided = false) THEN
        RAISE EXCEPTION 'This motion already has a resolution. Void the motion resolution first.';
      END IF;
      UPDATE public.case_motions SET is_voided = true, voided_at = now(), voided_by_user_id = p_voided_by_user_id, void_reason = p_void_reason, updated_by_user_id = p_voided_by_user_id, updated_at = now() WHERE id = v_motion_id;
      SELECT to_jsonb(cm) INTO v_motion_new FROM public.case_motions cm WHERE cm.id = v_motion_id;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_motions',v_motion_id,'VOID_MOTION_RECEIVED_FROM_EVENT',v_motion_old,v_motion_new,v_case_id,'Motion Received voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_motion_resolution_approvals' OR v_event_type_code = 'MOTION_DECISION_APPROVED' THEN
    SELECT cmra.id, to_jsonb(cmra) INTO v_motion_decision_approval_id, v_motion_decision_approval_old
    FROM public.case_motion_resolution_approvals cmra
    WHERE cmra.id = v_source_id OR cmra.case_event_id = p_case_event_id
    ORDER BY CASE WHEN cmra.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_motion_decision_approval_id IS NOT NULL THEN
      UPDATE public.case_motion_resolution_approvals
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      WHERE id = v_motion_decision_approval_id;

      SELECT to_jsonb(cmra) INTO v_motion_decision_approval_new
      FROM public.case_motion_resolution_approvals cmra
      WHERE cmra.id = v_motion_decision_approval_id;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_motion_resolution_approvals',v_motion_decision_approval_id,'VOID_MOTION_DECISION_APPROVED_FROM_EVENT',v_motion_decision_approval_old,v_motion_decision_approval_new,v_case_id,'Motion Decision Approved voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_motion_resolutions' OR v_event_type_code = 'MOTION_RESOLVED' THEN
    SELECT cmr.id, to_jsonb(cmr) INTO v_motion_resolution_id, v_motion_resolution_old
    FROM public.case_motion_resolutions cmr
    WHERE cmr.id = v_source_id OR cmr.case_event_id = p_case_event_id
    ORDER BY CASE WHEN cmr.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_motion_resolution_id IS NOT NULL THEN
      SELECT count(*) INTO v_motion_approval_count
      FROM public.case_motion_resolution_approvals cmra
      WHERE cmra.case_motion_resolution_id = v_motion_resolution_id
        AND cmra.is_voided = false;
      IF COALESCE(v_motion_approval_count, 0) > 0 THEN
        RAISE EXCEPTION 'This motion resolution already has an approved decision. Void the approval event first.';
      END IF;

      UPDATE public.case_motion_resolutions
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      WHERE id = v_motion_resolution_id;

      SELECT to_jsonb(cmr) INTO v_motion_resolution_new
      FROM public.case_motion_resolutions cmr
      WHERE cmr.id = v_motion_resolution_id;

      UPDATE public.case_motions cm
      SET motion_status = 'PENDING',
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      FROM public.case_motion_resolutions cmr
      WHERE cm.id = cmr.case_motion_id
        AND cmr.id = v_motion_resolution_id
        AND cm.is_voided = false;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_motion_resolutions',v_motion_resolution_id,'VOID_MOTION_RESOLVED_FROM_EVENT',v_motion_resolution_old,v_motion_resolution_new,v_case_id,'Motion Resolved voided and case status/stage recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_court_filings' OR v_event_type_code = 'COURT_FILING' THEN
    SELECT cf.id, to_jsonb(cf) INTO v_filing_id, v_filing_old FROM public.case_court_filings cf WHERE cf.id = v_source_id OR cf.case_event_id = p_case_event_id ORDER BY CASE WHEN cf.id = v_source_id THEN 0 ELSE 1 END LIMIT 1;
    IF v_filing_id IS NOT NULL THEN
      UPDATE public.case_court_filings SET is_voided = true, voided_at = now(), voided_by_user_id = p_voided_by_user_id, void_reason = p_void_reason, updated_by_user_id = p_voided_by_user_id, updated_at = now() WHERE id = v_filing_id;
      SELECT to_jsonb(cf) INTO v_filing_new FROM public.case_court_filings cf WHERE cf.id = v_filing_id;

      PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

      SELECT to_jsonb(cpd) INTO v_new_details
      FROM public.case_private_details cpd
      WHERE cpd.case_id = v_case_id;

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (p_voided_by_user_id,'case_court_filings',v_filing_id,'VOID_COURT_FILING_FROM_EVENT',v_filing_old,jsonb_build_object('court_filing',v_filing_new,'case_private_details',v_new_details),v_case_id,'Court filing voided and case status recomputed.',jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason));
    END IF;
  END IF;

  IF v_event_type_code = 'CASE_ASSIGNMENT' THEN
    SELECT ca.id, to_jsonb(ca) INTO v_assignment_id, v_assignment_old
    FROM public.case_assignments ca
    WHERE ca.id = v_source_id OR ca.case_event_id = p_case_event_id
    ORDER BY CASE WHEN ca.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_assignment_id IS NOT NULL THEN
      UPDATE public.case_assignments
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          unassigned_at = COALESCE(unassigned_at, now())
      WHERE id = v_assignment_id;

      SELECT to_jsonb(ca) INTO v_assignment_new
      FROM public.case_assignments ca
      WHERE ca.id = v_assignment_id;

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (
        p_voided_by_user_id,
        'case_assignments',
        v_assignment_id,
        'VOID_CASE_ASSIGNMENT_FROM_EVENT',
        v_assignment_old,
        v_assignment_new,
        v_case_id,
        'Assignment row voided because the Case Assignment event was voided.',
        jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason)
      );
    END IF;
  ELSIF v_event_type_code = 'CASE_REASSIGNMENT' THEN
    v_previous_assignment_id := NULLIF(v_old#>>'{details_jsonb,previous_assignment_id}', '')::bigint;

    SELECT ca.id, to_jsonb(ca) INTO v_assignment_id, v_assignment_old
    FROM public.case_assignments ca
    WHERE ca.id = v_source_id OR ca.case_event_id = p_case_event_id
    ORDER BY CASE WHEN ca.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    SELECT ca.id INTO v_latest_assignment_id
    FROM public.case_assignments ca
    WHERE ca.case_id = v_case_id
      AND ca.is_voided IS FALSE
    ORDER BY ca.assigned_at DESC NULLS LAST, ca.id DESC
    LIMIT 1;

    IF v_assignment_id IS NULL OR v_latest_assignment_id IS DISTINCT FROM v_assignment_id THEN
      RAISE EXCEPTION 'This reassignment has already been superseded by a later assignment. Void the latest reassignment first.';
    END IF;

    UPDATE public.case_assignments
    SET is_voided = true,
        voided_at = now(),
        voided_by_user_id = p_voided_by_user_id,
        void_reason = p_void_reason,
        unassigned_at = COALESCE(unassigned_at, now())
    WHERE id = v_assignment_id;

    SELECT to_jsonb(ca) INTO v_assignment_new
    FROM public.case_assignments ca
    WHERE ca.id = v_assignment_id;

    IF v_previous_assignment_id IS NOT NULL THEN
      SELECT to_jsonb(ca) INTO v_previous_assignment_old
      FROM public.case_assignments ca
      WHERE ca.id = v_previous_assignment_id
        AND ca.case_id = v_case_id
      FOR UPDATE;

      IF v_previous_assignment_old IS NOT NULL THEN
        UPDATE public.case_assignments
        SET unassigned_at = NULL,
            unassigned_by_user_id = NULL,
            unassignment_reason = NULL
        WHERE id = v_previous_assignment_id
          AND case_id = v_case_id
          AND is_voided IS FALSE;

        SELECT to_jsonb(ca) INTO v_previous_assignment_new
        FROM public.case_assignments ca
        WHERE ca.id = v_previous_assignment_id;
      END IF;
    END IF;

    INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
    VALUES (
      p_voided_by_user_id,
      'case_assignments',
      v_assignment_id,
      'VOID_CASE_REASSIGNMENT_NEW_ASSIGNMENT',
      v_assignment_old,
      v_assignment_new,
      v_case_id,
      'Reassignment-created assignment row voided because the Case Reassignment event was voided.',
      jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason,'previous_assignment_id',v_previous_assignment_id)
    );

    IF v_previous_assignment_old IS NOT NULL THEN
      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (
        p_voided_by_user_id,
        'case_assignments',
        v_previous_assignment_id,
        'RESTORE_PREVIOUS_ASSIGNMENT_FROM_REASSIGNMENT_VOID',
        v_previous_assignment_old,
        v_previous_assignment_new,
        v_case_id,
        'Previous assignment restored because the Case Reassignment event was voided.',
        jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason,'voided_assignment_id',v_assignment_id)
      );
    END IF;
  ELSIF lower(coalesce(v_source_table,'')) = 'case_assignments' THEN
    UPDATE public.case_assignments
    SET is_voided = true,
        voided_at = now(),
        voided_by_user_id = p_voided_by_user_id,
        void_reason = p_void_reason,
        unassigned_at = COALESCE(unassigned_at, now())
    WHERE id = v_source_id OR case_event_id = p_case_event_id;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_resolutions' OR v_event_type_code = 'CASE_RESOLVED' THEN
    SELECT cr.id INTO v_resolution_id FROM public.case_resolutions cr WHERE cr.id = v_source_id OR cr.case_event_id = p_case_event_id LIMIT 1;
    IF v_resolution_id IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.case_resolution_approvals a WHERE a.case_resolution_id = v_resolution_id AND a.is_voided = false) THEN
        RAISE EXCEPTION 'This resolution already has approved decisions. Void the approval events first.';
      END IF;
      UPDATE public.case_resolutions SET is_voided=true, voided_at=now(), voided_by_user_id=p_voided_by_user_id, void_reason=p_void_reason, updated_by_user_id=p_voided_by_user_id, updated_at=now() WHERE id=v_resolution_id;
    END IF;
  END IF;

  IF lower(coalesce(v_source_table,'')) = 'case_resolution_approvals' OR v_event_type_code = 'CASE_DECISION_APPROVED' THEN
    SELECT a.id INTO v_approval_id FROM public.case_resolution_approvals a WHERE a.id = v_source_id OR a.case_event_id = p_case_event_id LIMIT 1;
    IF v_approval_id IS NOT NULL THEN
      UPDATE public.case_resolution_approvals SET is_voided=true, voided_at=now(), voided_by_user_id=p_voided_by_user_id, void_reason=p_void_reason, updated_by_user_id=p_voided_by_user_id, updated_at=now() WHERE id=v_approval_id;
    END IF;
  END IF;

  IF v_event_type_code IN ('CASE_RESOLVED','CASE_DECISION_APPROVED','CASE_ASSIGNMENT','CASE_REASSIGNMENT')
     OR lower(coalesce(v_source_table,'')) IN ('case_resolutions','case_resolution_approvals','case_assignments') THEN
    PERFORM public.apply_case_state_recompute(v_case_id, CURRENT_DATE, NULL, p_case_event_id, p_voided_by_user_id);

    IF v_event_type_code = 'CASE_REASSIGNMENT' THEN
      SELECT to_jsonb(cpd) INTO v_new_details
      FROM public.case_private_details cpd
      WHERE cpd.case_id = v_case_id;

      INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata)
      VALUES (
        p_voided_by_user_id,
        'case_private_details',
        v_case_id,
        'CASE_REASSIGNMENT_VOID_STATUS_STAGE_RECOMPUTED',
        v_old_details,
        v_new_details,
        v_case_id,
        'Case Reassignment voided; case status and case stage recomputed from active workflow records.',
        jsonb_build_object('case_event_id',p_case_event_id,'reason',p_void_reason,'restored_assignment_id',v_previous_assignment_id,'voided_assignment_id',v_assignment_id)
      );
    END IF;
  END IF;

END;
$$;


GRANT EXECUTE ON FUNCTION public.void_case_event(bigint, text, bigint) TO authenticated;

COMMENT ON FUNCTION public.compute_current_case_state(bigint) IS 'Manual Case Status Updated and Petition Update explicit statuses share deterministic explicit-state recompute after genuinely unfinished Motion/Resolution/Filing checks; an active Petition with no explicit update remains PENDING/PENDING_PETREV. Latest explicit state uses effective date DESC, effective time DESC NULLS LAST, case_event_id DESC, source id DESC.';
COMMENT ON FUNCTION public.record_case_status_updated_event(bigint,bigint,bigint,date,text,text,bigint) IS 'Records a voidable CASE_STATUS_UPDATED timeline event and synchronized Case Status / Case Stage current state with conditional history linked to the event.';
COMMENT ON FUNCTION public.void_case_event(bigint,text,bigint) IS 'Includes CASE_STATUS_UPDATED void branch, marks manual status update rows voided, preserves voided timeline events, and invokes shared recompute once while preserving unrelated branches.';

-- Verification notes:
-- 1. Active Petition without an applicable explicit update recomputes to PENDING / PENDING_PETREV.
-- 1a. record_case_status_updated_event creates exactly one CASE_STATUS_UPDATED case_events row.
-- 2. Selected Case Status and Case Stage are stored on case_events and case_private_details.
-- 3. case_status_history and case_stage_history rows link to the CASE_STATUS_UPDATED event when values change.
-- 4. CASE_STATUS_UPDATED events are normal timeline rows and use public.void_case_event.
-- 5. Voiding a manual update with only assignment remaining recomputes to PENDING / CASE_RAFFLED.
-- 6. Voiding a manual update with Court Filing remaining recomputes to FILED / FILED.
-- 7. Multiple manual updates act as an explicit-state stack ordered by event_date, event_time, event id, and source id.
-- 8. Active pending Motion / Motion Resolution awaiting approval temporarily overrides manual updates.
-- 9. Voiding the Motion path reveals the latest active manual update again.
-- 10. Active Petition for Review without an explicit update temporarily overrides manual updates.
-- 10a. Petition Update with Update Case Status = Yes remains eligible in the same explicit-state ordering as manual updates.
-- 10b. A later CASE_STATUS_UPDATED supersedes an earlier Petition Update; a later Petition Update supersedes an earlier CASE_STATUS_UPDATED.
-- 11. Voiding the Petition removes its Petition Updates from recomputation and recomputes from remaining active records.
-- 12. Voided case_manual_status_updates and voided CASE_STATUS_UPDATED events never influence recompute.
-- 13. The CASE_STATUS_UPDATED void branch calls public.apply_case_state_recompute exactly once.
-- 14. Add Case Stage behavior is preserved unchanged from PR 106.
-- 15. Unrelated event branches in public.void_case_event are preserved from the latest implementation.

COMMIT;
