-- Court Status Update is an in-place enrichment of an existing active COURT_FILING event.
-- Verification coverage:
-- 1. The COURT_STATUS_UPDATE seed sort_order is set to 145, between COURT_FILING (140) and MOTION_RECEIVED (150).
-- 2. UI queries filter case_court_filings by case_id, is_voided=false, and active linked case_events.
-- 3. UI auto-selects when one eligible filing exists.
-- 4. UI shows “No active Court Filing is available for update.” when none exist.
-- 5. UI renders original filing details as read-only labels.
-- 6-12. RPC validates/saves multiple criminal numbers, court statuses, information_count, and ordered additional details.
-- 13-17. RPC updates existing rows only, preserves event date/time/status/stage, and does not insert status/stage history.
-- 18-19. Existing COURT_FILING details_jsonb is enriched for timeline display and workflow reload.
-- 20. RPC writes UPDATE_COURT_FILING_STATUS_DETAILS audit log with before/after data.
-- 21. Migration does not alter unrelated event RPCs, recompute helpers, or public.void_case_event.
-- 22. TypeScript check is expected to pass after frontend changes.
-- 23. Removing all Criminal Case Number rows and Court Status rows sets legacy case_court_filings.criminal_case_no and case_court_filings.court_status to NULL, so reopening the form cannot repopulate deleted legacy values.

UPDATE public.case_event_types SET sort_order = 145, updated_at = now() WHERE code = 'COURT_STATUS_UPDATE';

ALTER TABLE public.case_court_filings
  ADD COLUMN IF NOT EXISTS additional_details_jsonb jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS court_status_update_remarks text;

CREATE TABLE IF NOT EXISTS public.case_court_filing_criminal_cases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  court_filing_id bigint NOT NULL REFERENCES public.case_court_filings(id),
  criminal_case_no text NOT NULL,
  sort_order integer,
  created_by_user_id bigint REFERENCES public.users(id),
  updated_by_user_id bigint REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_voided boolean NOT NULL DEFAULT false,
  voided_at timestamptz,
  voided_by_user_id bigint REFERENCES public.users(id),
  void_reason text
);

CREATE TABLE IF NOT EXISTS public.case_court_filing_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  court_filing_id bigint NOT NULL REFERENCES public.case_court_filings(id),
  court_status text NOT NULL,
  status_date date NOT NULL,
  sort_order integer,
  remarks text,
  created_by_user_id bigint REFERENCES public.users(id),
  updated_by_user_id bigint REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_voided boolean NOT NULL DEFAULT false,
  voided_at timestamptz,
  voided_by_user_id bigint REFERENCES public.users(id),
  void_reason text
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_case_court_filing_criminal_cases_active_no ON public.case_court_filing_criminal_cases(court_filing_id, lower(criminal_case_no)) WHERE is_voided = false;
CREATE UNIQUE INDEX IF NOT EXISTS uq_case_court_filing_statuses_active_status_date ON public.case_court_filing_statuses(court_filing_id, lower(court_status), status_date) WHERE is_voided = false;
CREATE INDEX IF NOT EXISTS idx_case_court_filing_criminal_cases_filing ON public.case_court_filing_criminal_cases(court_filing_id) WHERE is_voided = false;
CREATE INDEX IF NOT EXISTS idx_case_court_filing_statuses_filing ON public.case_court_filing_statuses(court_filing_id) WHERE is_voided = false;

CREATE OR REPLACE FUNCTION public.update_court_filing_status_details(
  p_case_id bigint,
  p_court_filing_id bigint,
  p_criminal_case_numbers jsonb DEFAULT '[]'::jsonb,
  p_court_statuses jsonb DEFAULT '[]'::jsonb,
  p_information_count integer DEFAULT NULL,
  p_additional_details_jsonb jsonb DEFAULT '[]'::jsonb,
  p_remarks text DEFAULT NULL,
  p_user_id bigint DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_filing public.case_court_filings%ROWTYPE;
  v_event public.case_events%ROWTYPE;
  v_old jsonb;
  v_new jsonb;
  v_numbers jsonb := '[]'::jsonb;
  v_statuses jsonb := '[]'::jsonb;
  v_details jsonb := '[]'::jsonb;
  v_item jsonb;
  v_text text;
  v_date date;
  v_idx integer := 0;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.cases WHERE id = p_case_id) THEN RAISE EXCEPTION 'Case does not exist'; END IF;
  SELECT * INTO v_filing FROM public.case_court_filings WHERE id = p_court_filing_id;
  IF v_filing.id IS NULL THEN RAISE EXCEPTION 'Court Filing does not exist'; END IF;
  IF v_filing.case_id <> p_case_id THEN RAISE EXCEPTION 'Court Filing does not belong to this case'; END IF;
  IF v_filing.is_voided THEN RAISE EXCEPTION 'Court Filing is not active'; END IF;
  SELECT * INTO v_event FROM public.case_events WHERE id = v_filing.case_event_id AND case_id = p_case_id AND is_voided = false;
  IF v_event.id IS NULL THEN RAISE EXCEPTION 'Linked Court Filing event is not active'; END IF;
  IF p_information_count IS NOT NULL AND p_information_count < 0 THEN RAISE EXCEPTION 'Information Count must be a non-negative integer'; END IF;
  IF p_criminal_case_numbers IS NOT NULL AND jsonb_typeof(p_criminal_case_numbers) <> 'array' THEN RAISE EXCEPTION 'Criminal Case Numbers must be a JSON array'; END IF;
  IF p_court_statuses IS NOT NULL AND jsonb_typeof(p_court_statuses) <> 'array' THEN RAISE EXCEPTION 'Court Statuses must be a JSON array'; END IF;
  IF p_additional_details_jsonb IS NOT NULL AND jsonb_typeof(p_additional_details_jsonb) <> 'array' THEN RAISE EXCEPTION 'Additional Details must be a JSON array'; END IF;

  SELECT jsonb_build_object('court_filing', to_jsonb(v_filing), 'event_details_jsonb', v_event.details_jsonb,
    'criminal_case_numbers', COALESCE(jsonb_agg(to_jsonb(cc) ORDER BY cc.sort_order, cc.id) FILTER (WHERE cc.id IS NOT NULL), '[]'::jsonb),
    'court_statuses', COALESCE((SELECT jsonb_agg(to_jsonb(cs) ORDER BY cs.sort_order, cs.id) FROM public.case_court_filing_statuses cs WHERE cs.court_filing_id=p_court_filing_id AND cs.is_voided=false), '[]'::jsonb))
  INTO v_old FROM public.case_court_filing_criminal_cases cc WHERE cc.court_filing_id=p_court_filing_id AND cc.is_voided=false;

  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_criminal_case_numbers,'[]'::jsonb)) LOOP
    v_text := nullif(btrim(CASE WHEN jsonb_typeof(v_item)='object' THEN v_item->>'criminal_case_no' ELSE trim(both '"' from v_item::text) END), '');
    IF v_text IS NOT NULL AND NOT v_numbers @> jsonb_build_array(v_text) THEN v_numbers := v_numbers || jsonb_build_array(v_text); END IF;
  END LOOP;

  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_court_statuses,'[]'::jsonb)) LOOP
    v_text := nullif(btrim(v_item->>'court_status'), '');
    IF v_text IS NULL AND nullif(btrim(v_item->>'status_date'), '') IS NULL THEN CONTINUE; END IF;
    IF v_text IS NULL OR nullif(btrim(v_item->>'status_date'), '') IS NULL THEN RAISE EXCEPTION 'Court Status and Status Date are required'; END IF;
    v_date := (v_item->>'status_date')::date;
    IF NOT v_statuses @> jsonb_build_array(jsonb_build_object('court_status', v_text, 'status_date', v_date)) THEN
      v_statuses := v_statuses || jsonb_build_array(jsonb_build_object('court_status', v_text, 'status_date', v_date));
    END IF;
  END LOOP;

  FOR v_item IN SELECT value FROM jsonb_array_elements(coalesce(p_additional_details_jsonb,'[]'::jsonb)) LOOP
    IF nullif(btrim(v_item->>'detail'), '') IS NOT NULL OR nullif(btrim(v_item->>'value'), '') IS NOT NULL THEN
      v_details := v_details || jsonb_build_array(jsonb_build_object('detail', btrim(coalesce(v_item->>'detail','')), 'value', btrim(coalesce(v_item->>'value',''))));
    END IF;
  END LOOP;

  UPDATE public.case_court_filing_criminal_cases SET is_voided=true, voided_at=now(), voided_by_user_id=p_user_id, void_reason='Removed by Court Status Update', updated_at=now(), updated_by_user_id=p_user_id WHERE court_filing_id=p_court_filing_id AND is_voided=false AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements_text(v_numbers) n WHERE lower(n.value)=lower(criminal_case_no));
  v_idx := 0;
  FOR v_text IN SELECT value FROM jsonb_array_elements_text(v_numbers) LOOP
    v_idx := v_idx + 1;
    INSERT INTO public.case_court_filing_criminal_cases(case_id,court_filing_id,criminal_case_no,sort_order,created_by_user_id,updated_by_user_id) VALUES(p_case_id,p_court_filing_id,v_text,v_idx,p_user_id,p_user_id)
    ON CONFLICT (court_filing_id, (lower(criminal_case_no))) WHERE is_voided=false DO UPDATE SET sort_order=EXCLUDED.sort_order, updated_at=now(), updated_by_user_id=p_user_id;
  END LOOP;

  UPDATE public.case_court_filing_statuses SET is_voided=true, voided_at=now(), voided_by_user_id=p_user_id, void_reason='Removed by Court Status Update', updated_at=now(), updated_by_user_id=p_user_id WHERE court_filing_id=p_court_filing_id AND is_voided=false AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(v_statuses) s WHERE lower(s.value->>'court_status')=lower(court_status) AND (s.value->>'status_date')::date=status_date);
  v_idx := 0;
  FOR v_item IN SELECT value FROM jsonb_array_elements(v_statuses) LOOP
    v_idx := v_idx + 1;
    INSERT INTO public.case_court_filing_statuses(case_id,court_filing_id,court_status,status_date,sort_order,remarks,created_by_user_id,updated_by_user_id) VALUES(p_case_id,p_court_filing_id,v_item->>'court_status',(v_item->>'status_date')::date,v_idx,p_remarks,p_user_id,p_user_id)
    ON CONFLICT (court_filing_id, (lower(court_status)), status_date) WHERE is_voided=false DO UPDATE SET sort_order=EXCLUDED.sort_order, remarks=EXCLUDED.remarks, updated_at=now(), updated_by_user_id=p_user_id;
  END LOOP;

  UPDATE public.case_court_filings SET information_count=p_information_count, additional_details_jsonb=v_details, court_status_update_remarks=nullif(btrim(coalesce(p_remarks,'')), ''), criminal_case_no=CASE WHEN jsonb_array_length(v_numbers) = 0 THEN NULL ELSE v_numbers->>0 END, court_status=CASE WHEN jsonb_array_length(v_statuses) = 0 THEN NULL ELSE (v_statuses->(jsonb_array_length(v_statuses)-1))->>'court_status' END, updated_at=now(), updated_by_user_id=p_user_id WHERE id=p_court_filing_id;

  SELECT jsonb_build_object('criminal_case_numbers', COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'criminal_case_no',criminal_case_no,'sort_order',sort_order) ORDER BY sort_order,id) FROM public.case_court_filing_criminal_cases WHERE court_filing_id=p_court_filing_id AND is_voided=false), '[]'::jsonb), 'court_statuses', COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'court_status',court_status,'status_date',status_date,'sort_order',sort_order) ORDER BY sort_order,id) FROM public.case_court_filing_statuses WHERE court_filing_id=p_court_filing_id AND is_voided=false), '[]'::jsonb)) INTO v_new;

  UPDATE public.case_events SET details_jsonb = COALESCE(details_jsonb,'{}'::jsonb) || jsonb_build_object('court_filing_id', p_court_filing_id, 'approved_filing_decision', v_event.details_jsonb->'approved_filing_decision', 'court', v_filing.court_name, 'court_branch', v_filing.court_branch, 'charge_filed', v_filing.charge_filed, 'date_filed', v_filing.date_filed, 'time_filed', v_filing.time_filed, 'criminal_case_numbers', v_new->'criminal_case_numbers', 'court_statuses', v_new->'court_statuses', 'information_count', p_information_count, 'additional_details', v_details, 'court_status_update_remarks', nullif(btrim(coalesce(p_remarks,'')), ''), 'last_court_status_updated_at', now(), 'last_court_status_updated_by_user_id', p_user_id), updated_at=now(), updated_by_user_id=p_user_id WHERE id=v_event.id;

  SELECT jsonb_build_object('court_filing', to_jsonb(cf), 'event_details_jsonb', ce.details_jsonb, 'criminal_case_numbers', v_new->'criminal_case_numbers', 'court_statuses', v_new->'court_statuses') INTO v_new FROM public.case_court_filings cf JOIN public.case_events ce ON ce.id=cf.case_event_id WHERE cf.id=p_court_filing_id;
  INSERT INTO public.audit_logs(actor_user_id,entity_name,entity_id,action,old_data,new_data,case_id,summary,metadata) VALUES(p_user_id,'case_court_filings',p_court_filing_id,'UPDATE_COURT_FILING_STATUS_DETAILS',v_old,v_new,p_case_id,'Court filing status details updated.',jsonb_build_object('case_event_id',v_event.id,'remarks',p_remarks));
  RETURN p_court_filing_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.update_court_filing_status_details(bigint,bigint,jsonb,jsonb,integer,jsonb,text,bigint) TO authenticated;
GRANT ALL ON TABLE public.case_court_filing_criminal_cases TO authenticated;
GRANT ALL ON TABLE public.case_court_filing_statuses TO authenticated;
