-- Trusted Google Drive folder mappings. OAuth credentials remain exclusively in the app server.
CREATE TABLE public.docket_year_drive_folders (
  docket_year integer NOT NULL,
  folder_id varchar(255),
  root_folder_id varchar(255) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'PENDING',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (docket_year, root_folder_id),
  CONSTRAINT docket_year_drive_folder_status CHECK (status IN ('PENDING','CREATING','READY','FAILED','DISCONNECTED'))
);

CREATE TABLE public.case_drive_folders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL UNIQUE REFERENCES public.cases(id) ON DELETE CASCADE,
  docket_year integer NOT NULL,
  folder_id varchar(255),
  parent_folder_id varchar(255) NOT NULL,
  folder_name text NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'PENDING',
  last_error text,
  last_scanned_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT case_drive_folder_status CHECK (status IN ('PENDING','CREATING','READY','FAILED','DISCONNECTED'))
);
CREATE INDEX case_drive_folders_year_idx ON public.case_drive_folders (docket_year);

-- A browser-generated key makes an API retry return the original RPC result instead of creating a second docket.
CREATE TABLE public.docket_creation_requests (
  auth_user_id uuid NOT NULL,
  idempotency_key uuid NOT NULL,
  status varchar(30) NOT NULL,
  case_id bigint UNIQUE REFERENCES public.cases(id) ON DELETE SET NULL,
  result jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (auth_user_id, idempotency_key),
  CONSTRAINT docket_creation_request_status CHECK (status IN ('CREATING','CREATED'))
);

ALTER TABLE public.docket_year_drive_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_drive_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.docket_creation_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY case_drive_folders_read ON public.case_drive_folders FOR SELECT TO authenticated
  USING (public.can_view_case_details(case_id));
GRANT SELECT ON public.case_drive_folders TO authenticated;
GRANT ALL ON public.docket_year_drive_folders, public.case_drive_folders, public.docket_creation_requests TO service_role;
CREATE OR REPLACE VIEW public.v_case_details_page WITH (security_invoker='true') AS
 WITH latest_assignment AS (
         SELECT DISTINCT ON (ca.case_id) ca.case_id,
            ca.prosecutor_id,
            ca.staff_id,
            ca.assigned_at,
            ca.id
           FROM public.case_assignments ca
          WHERE ca.unassigned_at IS NULL AND COALESCE(ca.is_voided, false) IS FALSE
          ORDER BY ca.case_id, ca.assigned_at DESC NULLS LAST, ca.id DESC
        ), violation_summary AS (
         SELECT cv.case_id,
            string_agg(COALESCE(NULLIF(btrim(cv.raw_violation_text), ''::text), v.title), ', '::text ORDER BY cv.violation_order, cv.id) AS violations
           FROM (public.case_violations cv
             LEFT JOIN public.violations v ON ((v.id = cv.violation_id)))
          WHERE COALESCE(cv.is_deleted, false) IS FALSE
          GROUP BY cv.case_id
        ), note_summary AS (
         SELECT n.case_id,
            jsonb_agg(jsonb_build_object('id', n.id, 'note_text', n.note_text, 'is_private', n.is_private, 'created_by_user_id', n.created_by_user_id, 'created_at', n.created_at, 'updated_at', n.updated_at) ORDER BY n.created_at DESC, n.id DESC) AS notes
           FROM public.notes n
          WHERE COALESCE(n.is_deleted, false) IS FALSE
          GROUP BY n.case_id
        ), case_address_summary AS (
         SELECT ca.case_id,
            jsonb_agg(jsonb_build_object('id', ca.id, 'address_id', ca.address_id, 'address_type_id', ca.address_type_id, 'address_type_label', at.display_label, 'is_primary', ca.is_primary, 'remarks', ca.remarks, 'addresses', jsonb_build_object('barangay', a.barangay, 'city', a.city, 'country', a.country, 'line1', a.line1, 'line2', a.line2, 'province', a.province, 'region', a.region, 'zip_code', a.zip_code)) ORDER BY ca.is_primary DESC, ca.id) AS case_addresses
           FROM ((public.case_addresses ca
             JOIN public.addresses a ON ((a.id = ca.address_id)))
             LEFT JOIN public.address_types at ON ((at.id = ca.address_type_id)))
          WHERE COALESCE(ca.is_deleted, false) IS FALSE
          GROUP BY ca.case_id
        )
 SELECT c.id,
    c.docket_type_id,
    c.docket_year,
    c.docket_number,
    c.docket_month_code,
    c.date_received,
    c.created_by_user_id,
    c.updated_by_user_id,
    c.is_archived,
    c.created_at,
    c.updated_at,
    c.region_code,
    c.case_classification_id,
    concat_ws('-'::text, c.region_code, dt.prefix, (right((c.docket_year)::text, 2) || COALESCE(c.docket_month_code, ''::text)), lpad((c.docket_number)::text, 6, '0'::text)) AS docket_display_number,
    dt.prefix AS docket_type_prefix,
    dt.name AS docket_type_name,
    vs.violations,
    cpd.source,
    cpd.remarks,
    cpd.legacy_source_file,
    cpd.legacy_source_sheet,
    cpd.legacy_row_number,
    cpd.legacy_raw_json,
    cpd.is_summary_procedure,
    cpd.summary_text,
    cpd.current_status_id,
    cpd.current_status_date,
    cpd.current_status_approved_date_raw,
    cpd.current_status_approved_date_raw AS status_approved_date_raw,
    NULL::date AS status_approved_date,
    cpd.current_status_raw,
    cpd.current_status_remarks,
    cs.code AS current_status_code,
    cs.display_label AS current_status_label,
    la.prosecutor_id AS current_prosecutor_id,
    p.short_name AS prosecutor_short_name,
    p.full_name AS prosecutor_full_name,
    la.staff_id AS current_staff_id,
    st.short_name AS staff_short_name,
    st.full_name AS staff_full_name,
    la.assigned_at AS current_assigned_at,
    NULL::text AS case_classification_code,
    NULL::text AS case_classification_name,
    cc.display_label AS case_classification_label,
    cc.description AS case_classification_description,
    cdf.folder_id::text AS gdrive_folder_id,
    CASE WHEN cdf.folder_id IS NULL THEN NULL::text ELSE 'https://drive.google.com/drive/folders/' || cdf.folder_id END AS gdrive_folder_link,
    cdf.folder_name AS gdrive_folder_name,
    cdf.status::text AS gdrive_folder_status,
    cdf.last_scanned_at AS gdrive_folder_last_scanned_at,
    NULL::text AS court_codes,
    NULL::text AS criminal_case_numbers,
    NULL::boolean AS court_needs_review,
    COALESCE(cas.case_addresses, '[]'::jsonb) AS case_addresses,
    COALESCE(ns.notes, '[]'::jsonb) AS notes,
    cpd.current_case_status_id,
    cpd.current_case_status_date,
    cpd.current_case_status_remarks,
    broad_status.code AS current_case_status_code,
    broad_status.display_label AS current_case_status_label,
    cpd.current_case_stage_id,
    cpd.current_case_stage_date,
    cpd.current_case_stage_remarks,
    stage.code AS current_case_stage_code,
    stage.display_label AS current_case_stage_label
   FROM (((((((((((((public.cases c
     JOIN public.docket_types dt ON ((dt.id = c.docket_type_id)))
     LEFT JOIN public.case_private_details cpd ON ((cpd.case_id = c.id)))
     LEFT JOIN public.case_statuses cs ON ((cs.id = cpd.current_status_id)))
     LEFT JOIN public.case_statuses broad_status ON ((broad_status.id = cpd.current_case_status_id)))
     LEFT JOIN public.case_stages stage ON ((stage.id = cpd.current_case_stage_id)))
     LEFT JOIN latest_assignment la ON ((la.case_id = c.id)))
     LEFT JOIN public.prosecutors p ON ((p.id = la.prosecutor_id)))
     LEFT JOIN public.staff st ON ((st.id = la.staff_id)))
     LEFT JOIN public.case_classifications cc ON ((cc.id = c.case_classification_id)))
     LEFT JOIN violation_summary vs ON ((vs.case_id = c.id)))
     LEFT JOIN note_summary ns ON ((ns.case_id = c.id)))
     LEFT JOIN case_address_summary cas ON ((cas.case_id = c.id)))
     LEFT JOIN public.case_drive_folders cdf ON ((cdf.case_id = c.id)))
  WHERE (NOT c.is_archived);

COMMENT ON VIEW public.v_case_details_page IS 'Case details page read model with legacy status plus split case status and case stage fields. Intentionally policy-free for development debugging.';
