ALTER TABLE public.prosecutors
ADD COLUMN IF NOT EXISTS position_code text;

ALTER TABLE public.prosecutors
DROP CONSTRAINT IF EXISTS prosecutors_position_code_check;

ALTER TABLE public.prosecutors
ADD CONSTRAINT prosecutors_position_code_check
CHECK (position_code IS NULL OR position_code IN ('CHIEF_PROSECUTOR', 'DEPUTY_PROSECUTOR', 'PROSECUTOR'));

CREATE OR REPLACE VIEW public.v_ref_prosecutors AS
 SELECT id,
    first_name,
    middle_name,
    last_name,
    suffix,
    full_name,
    short_name,
    position_id,
    is_active,
    created_at,
    position_code
   FROM public.prosecutors
  WHERE (is_active = true);

INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
VALUES ('CASE_DECISION_APPROVED', 'Case Decision Approved', 'CASE', 'Manual timeline event for approving a prosecutor recommendation or final case decision.', 130, true, true)
ON CONFLICT (code) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
VALUES
  ('FOR_FILING', 'For Filing', 90, true, true, true),
  ('DISMISSED', 'Dismissed', 100, true, true, true),
  ('MIXED_RESULT', 'Mixed Result', 110, true, true, true)
ON CONFLICT (code) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  sort_order = EXCLUDED.sort_order,
  is_final = true,
  is_milestone = true,
  is_active = true;

CREATE TABLE IF NOT EXISTS public.case_resolution_approvals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  case_event_id bigint NOT NULL UNIQUE REFERENCES public.case_events(id),
  case_resolution_id bigint REFERENCES public.case_resolutions(id),
  approved_by_prosecutor_id bigint NOT NULL REFERENCES public.prosecutors(id),
  date_approved date NOT NULL,
  time_approved time without time zone,
  final_status_code text NOT NULL,
  remarks text,
  created_by_user_id bigint REFERENCES public.users(id),
  updated_by_user_id bigint REFERENCES public.users(id),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT case_resolution_approvals_final_status_code_check CHECK (final_status_code IN ('FOR_FILING', 'DISMISSED', 'MIXED_RESULT'))
);

CREATE TABLE IF NOT EXISTS public.case_resolution_approval_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_id bigint NOT NULL REFERENCES public.case_resolution_approvals(id) ON DELETE CASCADE,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  source_resolution_charge_action_id bigint REFERENCES public.case_resolution_charge_actions(id),
  case_violation_id bigint REFERENCES public.case_violations(id),
  violation_id bigint REFERENCES public.violations(id),
  charge_text text NOT NULL,
  decision_code text NOT NULL,
  display_order integer NOT NULL,
  remarks text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT case_resolution_approval_actions_decision_code_check CHECK (decision_code IN ('FOR_FILING', 'DISMISSAL'))
);

CREATE INDEX IF NOT EXISTS idx_case_resolution_approvals_case_id ON public.case_resolution_approvals(case_id);
CREATE INDEX IF NOT EXISTS idx_case_resolution_approval_actions_approval_id ON public.case_resolution_approval_actions(approval_id);
CREATE INDEX IF NOT EXISTS idx_case_resolution_approval_actions_case_id ON public.case_resolution_approval_actions(case_id);

CREATE OR REPLACE FUNCTION public.record_case_decision_approved_event(
  p_case_id bigint,
  p_case_resolution_id bigint DEFAULT NULL,
  p_approved_by_prosecutor_id bigint DEFAULT NULL,
  p_date_approved date DEFAULT NULL,
  p_time_approved time without time zone DEFAULT NULL,
  p_approval_actions jsonb DEFAULT '[]'::jsonb,
  p_remarks text DEFAULT NULL,
  p_user_id bigint DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_type_id bigint;
  v_status_id bigint;
  v_previous_status_id bigint;
  v_event_id bigint;
  v_approval_id bigint;
  v_status_history_id bigint;
  v_approver_name text;
  v_approver_position_code text;
  v_final_status_code text;
  v_final_status_label text;
  v_remarks text := NULLIF(btrim(COALESCE(p_remarks, '')), '');
  v_old_details jsonb;
  v_new_details jsonb;
  v_action jsonb;
  v_action_count integer;
  v_for_filing_count integer;
  v_dismissal_count integer;
  v_display_order integer := 0;
BEGIN
  IF p_case_id IS NULL THEN RAISE EXCEPTION 'Case id is required'; END IF;
  IF p_approved_by_prosecutor_id IS NULL THEN RAISE EXCEPTION 'Approved by prosecutor is required'; END IF;
  IF p_date_approved IS NULL THEN RAISE EXCEPTION 'Date approved is required'; END IF;
  IF jsonb_typeof(COALESCE(p_approval_actions, '[]'::jsonb)) <> 'array' THEN RAISE EXCEPTION 'Approval actions must be an array'; END IF;

  IF NOT EXISTS (SELECT 1 FROM public.cases WHERE id = p_case_id) THEN
    RAISE EXCEPTION 'Unknown case id %', p_case_id;
  END IF;

  SELECT full_name, position_code INTO v_approver_name, v_approver_position_code
  FROM public.prosecutors
  WHERE id = p_approved_by_prosecutor_id AND is_active = true;

  IF v_approver_name IS NULL THEN RAISE EXCEPTION 'Unknown prosecutor id %', p_approved_by_prosecutor_id; END IF;
  IF COALESCE(v_approver_position_code, '') NOT IN ('CHIEF_PROSECUTOR', 'DEPUTY_PROSECUTOR') THEN
    RAISE EXCEPTION 'Approver must be a Chief Prosecutor or Deputy Prosecutor';
  END IF;

  IF p_case_resolution_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.case_resolutions WHERE id = p_case_resolution_id AND case_id = p_case_id) THEN
    RAISE EXCEPTION 'Resolution % does not belong to case %', p_case_resolution_id, p_case_id;
  END IF;

  SELECT count(*), count(*) FILTER (WHERE action.value->>'decision_code' = 'FOR_FILING'), count(*) FILTER (WHERE action.value->>'decision_code' = 'DISMISSAL')
  INTO v_action_count, v_for_filing_count, v_dismissal_count
  FROM jsonb_array_elements(COALESCE(p_approval_actions, '[]'::jsonb)) AS action(value)
  WHERE NULLIF(btrim(COALESCE(action.value->>'charge_text', '')), '') IS NOT NULL
    AND action.value->>'decision_code' IN ('FOR_FILING', 'DISMISSAL');

  IF v_action_count < 1 THEN RAISE EXCEPTION 'At least one approval action is required'; END IF;

  v_final_status_code := CASE
    WHEN v_for_filing_count = v_action_count THEN 'FOR_FILING'
    WHEN v_dismissal_count = v_action_count THEN 'DISMISSED'
    ELSE 'MIXED_RESULT'
  END;
  v_final_status_label := CASE v_final_status_code WHEN 'FOR_FILING' THEN 'For Filing' WHEN 'DISMISSED' THEN 'Dismissed' ELSE 'Mixed Result' END;

  INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
  VALUES ('CASE_DECISION_APPROVED', 'Case Decision Approved', 'CASE', 'Manual timeline event for approving a prosecutor recommendation or final case decision.', 130, true, true)
  ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, category = EXCLUDED.category, description = EXCLUDED.description, sort_order = EXCLUDED.sort_order, is_active = true, updated_at = now()
  RETURNING id INTO v_event_type_id;

  INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
  VALUES (v_final_status_code, v_final_status_label, CASE v_final_status_code WHEN 'FOR_FILING' THEN 90 WHEN 'DISMISSED' THEN 100 ELSE 110 END, true, true, true)
  ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, sort_order = EXCLUDED.sort_order, is_final = true, is_milestone = true, is_active = true
  RETURNING id INTO v_status_id;

  SELECT cpd.current_status_id, to_jsonb(cpd) INTO v_previous_status_id, v_old_details
  FROM public.case_private_details cpd WHERE cpd.case_id = p_case_id;

  INSERT INTO public.case_events (case_id, event_type_id, event_date, event_time, title, description, status_id, details_jsonb, source, created_by_user_id, updated_by_user_id)
  VALUES (p_case_id, v_event_type_id, p_date_approved, p_time_approved, 'Case Decision Approved', 'Decision approved by Prosec ' || v_approver_name || ' on ' || to_char(p_date_approved, 'Mon FMDD, YYYY'), v_status_id,
    jsonb_build_object('approved_by_prosecutor_id', p_approved_by_prosecutor_id, 'approved_by_name', v_approver_name, 'date_approved', p_date_approved, 'time_approved', p_time_approved, 'final_status_code', v_final_status_code, 'final_status_label', v_final_status_label, 'remarks', v_remarks),
    'MANUAL_ENTRY', p_user_id, p_user_id)
  RETURNING id INTO v_event_id;

  INSERT INTO public.case_resolution_approvals (case_id, case_event_id, case_resolution_id, approved_by_prosecutor_id, date_approved, time_approved, final_status_code, remarks, created_by_user_id, updated_by_user_id)
  VALUES (p_case_id, v_event_id, p_case_resolution_id, p_approved_by_prosecutor_id, p_date_approved, p_time_approved, v_final_status_code, v_remarks, p_user_id, p_user_id)
  RETURNING id INTO v_approval_id;

  FOR v_action IN SELECT * FROM jsonb_array_elements(COALESCE(p_approval_actions, '[]'::jsonb)) LOOP
    IF NULLIF(btrim(COALESCE(v_action->>'charge_text', '')), '') IS NOT NULL AND v_action->>'decision_code' IN ('FOR_FILING', 'DISMISSAL') THEN
      v_display_order := v_display_order + 1;
      INSERT INTO public.case_resolution_approval_actions (approval_id, case_id, source_resolution_charge_action_id, case_violation_id, violation_id, charge_text, decision_code, display_order, remarks)
      VALUES (v_approval_id, p_case_id, NULLIF(v_action->>'source_resolution_charge_action_id', '')::bigint, NULLIF(v_action->>'case_violation_id', '')::bigint, NULLIF(v_action->>'violation_id', '')::bigint, NULLIF(btrim(v_action->>'charge_text'), ''), v_action->>'decision_code', v_display_order, NULLIF(btrim(COALESCE(v_action->>'remarks', '')), ''));
    END IF;
  END LOOP;

  UPDATE public.case_events
  SET source_table = 'case_resolution_approvals', source_id = v_approval_id,
      details_jsonb = details_jsonb || jsonb_build_object('approval_actions', COALESCE((SELECT jsonb_agg(jsonb_build_object('id', aa.id, 'source_resolution_charge_action_id', aa.source_resolution_charge_action_id, 'case_violation_id', aa.case_violation_id, 'violation_id', aa.violation_id, 'charge_text', aa.charge_text, 'decision_code', aa.decision_code, 'display_order', aa.display_order, 'remarks', aa.remarks) ORDER BY aa.display_order, aa.id) FROM public.case_resolution_approval_actions aa WHERE aa.approval_id = v_approval_id), '[]'::jsonb)),
      updated_by_user_id = p_user_id, updated_at = now()
  WHERE id = v_event_id;

  INSERT INTO public.case_private_details (case_id, current_status_id, current_status_date, current_status_remarks, updated_at)
  VALUES (p_case_id, v_status_id, p_date_approved, v_remarks, now())
  ON CONFLICT (case_id) DO UPDATE SET current_status_id = EXCLUDED.current_status_id, current_status_date = EXCLUDED.current_status_date, current_status_remarks = EXCLUDED.current_status_remarks, updated_at = now();

  INSERT INTO public.case_status_history (case_id, from_status_id, to_status_id, changed_by_user_id, changed_at, status_date, remarks, case_event_id)
  VALUES (p_case_id, v_previous_status_id, v_status_id, p_user_id, now(), p_date_approved, v_remarks, v_event_id)
  RETURNING id INTO v_status_history_id;

  SELECT to_jsonb(cpd) INTO v_new_details FROM public.case_private_details cpd WHERE cpd.case_id = p_case_id;

  INSERT INTO public.audit_logs (actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata)
  VALUES (p_user_id, 'case_resolution_approvals', v_approval_id, 'CASE_DECISION_APPROVED', v_old_details, v_new_details, p_case_id, 'Case decision approved as ' || v_final_status_label || '.', jsonb_build_object('case_event_id', v_event_id, 'status_history_id', v_status_history_id, 'final_status_code', v_final_status_code));

  RETURN v_event_id;
END;
$$;
