-- A PE docket may be converted once to either an INV or INQ docket.  Keep the
-- relationship normalized and expose it only through read views.
CREATE TABLE IF NOT EXISTS public.case_docket_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pe_case_id bigint NOT NULL REFERENCES public.cases(id) ON DELETE RESTRICT,
  linked_case_id bigint NOT NULL REFERENCES public.cases(id) ON DELETE RESTRICT,
  linked_docket_kind text NOT NULL CHECK (linked_docket_kind IN ('INV', 'INQ')),
  created_by_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT case_docket_links_distinct_cases CHECK (pe_case_id <> linked_case_id),
  CONSTRAINT case_docket_links_pe_case_unique UNIQUE (pe_case_id),
  CONSTRAINT case_docket_links_linked_case_unique UNIQUE (linked_case_id)
);

CREATE INDEX IF NOT EXISTS case_docket_links_linked_case_id_idx ON public.case_docket_links(linked_case_id);

CREATE OR REPLACE VIEW public.v_case_linked_dockets WITH (security_invoker = true) AS
SELECT
  c.id,
  l.pe_case_id,
  l.linked_case_id,
  concat_ws('-', pe_dt.prefix, pe.docket_year::text, nullif(pe.docket_month_code, ''), lpad(pe.docket_number::text, 6, '0')) AS pe_docket_number,
  concat_ws('-', linked_dt.prefix, linked.docket_year::text, nullif(linked.docket_month_code, ''), lpad(linked.docket_number::text, 6, '0')) AS linked_docket_number,
  linked_dt.prefix AS linked_docket_type_prefix
FROM public.cases c
LEFT JOIN public.case_docket_links l ON l.pe_case_id = c.id OR l.linked_case_id = c.id
LEFT JOIN public.cases pe ON pe.id = l.pe_case_id
LEFT JOIN public.docket_types pe_dt ON pe_dt.id = pe.docket_type_id
LEFT JOIN public.cases linked ON linked.id = l.linked_case_id
LEFT JOIN public.docket_types linked_dt ON linked_dt.id = linked.docket_type_id;

-- Link after the established creator has performed all its validation and
-- inserts, so a failure rolls back both the new docket and its relationship.
CREATE OR REPLACE FUNCTION public.create_linked_docket_entry(p_payload jsonb, p_pe_case_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  v_result jsonb;
  v_new_case_id bigint;
  v_user_id bigint;
  v_pe_prefix text;
  v_target_prefix text;
BEGIN
  SELECT id INTO v_user_id FROM public.users WHERE auth_user_id = auth.uid() AND is_active IS TRUE;
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Authenticated application user is required'; END IF;
  SELECT dt.prefix INTO v_pe_prefix FROM public.cases c JOIN public.docket_types dt ON dt.id = c.docket_type_id WHERE c.id = p_pe_case_id AND NOT c.is_archived;
  IF upper(coalesce(v_pe_prefix, '')) <> 'PE' THEN RAISE EXCEPTION 'Only a PE docket can be linked'; END IF;
  SELECT prefix INTO v_target_prefix FROM public.docket_types WHERE id = (p_payload->>'docketTypeId')::bigint;
  IF upper(coalesce(v_target_prefix, '')) NOT IN ('INV', 'INQ') THEN RAISE EXCEPTION 'Linked PE dockets must be created as INV or INQ'; END IF;
  IF EXISTS (SELECT 1 FROM public.case_docket_links WHERE pe_case_id = p_pe_case_id) THEN RAISE EXCEPTION 'This PE docket is already linked'; END IF;
  v_result := public.create_new_docket_entry(p_payload);
  v_new_case_id := (v_result->>'caseId')::bigint;
  INSERT INTO public.case_docket_links(pe_case_id, linked_case_id, linked_docket_kind, created_by_user_id) VALUES (p_pe_case_id, v_new_case_id, upper(v_target_prefix), v_user_id);
  RETURN v_result;
END;
$$;

GRANT SELECT ON public.case_docket_links, public.v_case_linked_dockets TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_linked_docket_entry(jsonb, bigint) TO authenticated;
