INSERT INTO public.positions (code, title, group_type, is_active)
VALUES
  ('CHIEF_PROSECUTOR', 'Chief Prosecutor', 'PROSECUTOR', true),
  ('DEPUTY_PROSECUTOR', 'Deputy Prosecutor', 'PROSECUTOR', true),
  ('PROSECUTOR', 'Prosecutor', 'PROSECUTOR', true)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  group_type = EXCLUDED.group_type,
  is_active = EXCLUDED.is_active;

CREATE OR REPLACE VIEW public.v_ref_prosecutors AS
 SELECT pr.id,
    pr.first_name,
    pr.middle_name,
    pr.last_name,
    pr.suffix,
    pr.full_name,
    pr.short_name,
    pr.position_id,
    pr.is_active,
    pr.created_at,
    p.code AS position_code,
    p.title AS position_title,
    p.group_type AS position_group_type
   FROM public.prosecutors pr
   LEFT JOIN public.positions p ON p.id = pr.position_id
  WHERE (pr.is_active = true);

INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
VALUES ('CASE_DECISION_APPROVED', 'Case Decision Approved', 'CASE', 'Manual timeline event for approving a prosecutor recommendation or final case decision.', 130, true, true)
ON CONFLICT (code) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
VALUES
  ('PENDING', 'Pending', 20, false, false, true),
  ('RESO_FOR_APPROVAL', 'Reso for Approval', 80, false, true, true),
  ('FOR_FILING', 'For Filing', 90, true, true, true),
  ('DISMISSED', 'Dismissed', 100, true, true, true),
  ('MIXED_RESULT', 'Mixed Result', 110, true, true, true)
ON CONFLICT (code) DO UPDATE SET
  display_label = EXCLUDED.display_label,
  sort_order = EXCLUDED.sort_order,
  is_final = EXCLUDED.is_final,
  is_milestone = EXCLUDED.is_milestone,
  is_active = true;

ALTER TABLE public.case_resolutions
  ADD COLUMN IF NOT EXISTS is_voided boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS voided_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS voided_by_user_id bigint REFERENCES public.users(id),
  ADD COLUMN IF NOT EXISTS void_reason text;

CREATE TABLE IF NOT EXISTS public.case_resolution_approvals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  case_event_id bigint NOT NULL UNIQUE REFERENCES public.case_events(id),
  case_resolution_id bigint REFERENCES public.case_resolutions(id),
  approved_by_prosecutor_id bigint NOT NULL REFERENCES public.prosecutors(id),
  date_approved date NOT NULL,
  time_approved time without time zone,
  final_status_code text NOT NULL,
  remarks text,
  created_by_user_id bigint REFERENCES public.users(id),
  updated_by_user_id bigint REFERENCES public.users(id),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  is_voided boolean DEFAULT false NOT NULL,
  voided_at timestamp with time zone,
  voided_by_user_id bigint REFERENCES public.users(id),
  void_reason text,
  CONSTRAINT case_resolution_approvals_final_status_code_check CHECK (final_status_code IN ('FOR_FILING', 'DISMISSED', 'MIXED_RESULT'))
);

ALTER TABLE public.case_resolution_approvals
  ADD COLUMN IF NOT EXISTS is_voided boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS voided_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS voided_by_user_id bigint REFERENCES public.users(id),
  ADD COLUMN IF NOT EXISTS void_reason text;

CREATE TABLE IF NOT EXISTS public.case_resolution_approval_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_id bigint NOT NULL REFERENCES public.case_resolution_approvals(id) ON DELETE CASCADE,
  case_id bigint NOT NULL REFERENCES public.cases(id),
  source_resolution_charge_action_id bigint REFERENCES public.case_resolution_charge_actions(id),
  case_violation_id bigint REFERENCES public.case_violations(id),
  violation_id bigint REFERENCES public.violations(id),
  charge_text text NOT NULL,
  decision_code text NOT NULL,
  display_order integer NOT NULL,
  remarks text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT case_resolution_approval_actions_decision_code_check CHECK (decision_code IN ('FOR_FILING', 'DISMISSAL'))
);

CREATE INDEX IF NOT EXISTS idx_case_resolution_approvals_case_id ON public.case_resolution_approvals(case_id);
CREATE INDEX IF NOT EXISTS idx_case_resolution_approval_actions_approval_id ON public.case_resolution_approval_actions(approval_id);
CREATE INDEX IF NOT EXISTS idx_case_resolution_approval_actions_case_id ON public.case_resolution_approval_actions(case_id);

CREATE OR REPLACE FUNCTION public.record_case_decision_approved_event(
  p_case_id bigint,
  p_case_resolution_id bigint DEFAULT NULL,
  p_approved_by_prosecutor_id bigint DEFAULT NULL,
  p_date_approved date DEFAULT NULL,
  p_time_approved time without time zone DEFAULT NULL,
  p_approval_actions jsonb DEFAULT '[]'::jsonb,
  p_remarks text DEFAULT NULL,
  p_user_id bigint DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_type_id bigint;
  v_status_id bigint;
  v_previous_status_id bigint;
  v_event_id bigint;
  v_approval_id bigint;
  v_status_history_id bigint;
  v_approver_name text;
  v_approver_position_code text;
  v_approver_position_group_type text;
  v_event_final_status_code text;
  v_event_final_status_label text;
  v_case_final_status_code text;
  v_case_final_status_label text;
  v_remarks text := NULLIF(btrim(COALESCE(p_remarks, '')), '');
  v_old_details jsonb;
  v_new_details jsonb;
  v_action jsonb;
  v_action_count integer;
  v_for_filing_count integer;
  v_dismissal_count integer;
  v_existing_for_filing_count integer;
  v_existing_dismissal_count integer;
  v_total_for_filing_count integer;
  v_total_dismissal_count integer;
  v_total_action_count integer;
  v_display_order integer := 0;
BEGIN
  IF p_case_id IS NULL THEN RAISE EXCEPTION 'Case id is required'; END IF;
  IF p_approved_by_prosecutor_id IS NULL THEN RAISE EXCEPTION 'Approved by prosecutor is required'; END IF;
  IF p_date_approved IS NULL THEN RAISE EXCEPTION 'Date approved is required'; END IF;
  IF jsonb_typeof(COALESCE(p_approval_actions, '[]'::jsonb)) <> 'array' THEN RAISE EXCEPTION 'Approval actions must be an array'; END IF;

  IF NOT EXISTS (SELECT 1 FROM public.cases WHERE id = p_case_id) THEN
    RAISE EXCEPTION 'Unknown case id %', p_case_id;
  END IF;

  SELECT pr.full_name, p.code, p.group_type INTO v_approver_name, v_approver_position_code, v_approver_position_group_type
  FROM public.prosecutors pr
  JOIN public.positions p ON p.id = pr.position_id
  WHERE pr.id = p_approved_by_prosecutor_id
    AND pr.is_active = true
    AND p.is_active = true;

  IF v_approver_name IS NULL THEN RAISE EXCEPTION 'Unknown prosecutor id %', p_approved_by_prosecutor_id; END IF;
  IF COALESCE(v_approver_position_group_type, '') <> 'PROSECUTOR' OR COALESCE(v_approver_position_code, '') NOT IN ('CHIEF_PROSECUTOR', 'DEPUTY_PROSECUTOR') THEN
    RAISE EXCEPTION 'Approver must be a Chief Prosecutor or Deputy Prosecutor';
  END IF;

  IF p_case_resolution_id IS NULL THEN
    RAISE EXCEPTION 'Case resolution id is required';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.case_resolutions WHERE id = p_case_resolution_id AND case_id = p_case_id) THEN
    RAISE EXCEPTION 'Resolution % does not belong to case %', p_case_resolution_id, p_case_id;
  END IF;

  IF EXISTS (SELECT 1 FROM public.case_resolutions WHERE id = p_case_resolution_id AND case_id = p_case_id AND is_voided = true) THEN
    RAISE EXCEPTION 'Voided resolution cannot be approved.';
  END IF;

  IF EXISTS (SELECT 1 FROM public.case_resolution_approvals WHERE case_resolution_id = p_case_resolution_id AND is_voided = false) THEN
    RAISE EXCEPTION 'This resolution already has an active approved decision.';
  END IF;

  SELECT count(*), count(*) FILTER (WHERE action.value->>'decision_code' = 'FOR_FILING'), count(*) FILTER (WHERE action.value->>'decision_code' = 'DISMISSAL')
  INTO v_action_count, v_for_filing_count, v_dismissal_count
  FROM jsonb_array_elements(COALESCE(p_approval_actions, '[]'::jsonb)) AS action(value)
  WHERE NULLIF(btrim(COALESCE(action.value->>'charge_text', '')), '') IS NOT NULL
    AND action.value->>'decision_code' IN ('FOR_FILING', 'DISMISSAL');

  IF v_action_count < 1 THEN RAISE EXCEPTION 'At least one approval action is required'; END IF;

  v_event_final_status_code := CASE
    WHEN v_for_filing_count = v_action_count THEN 'FOR_FILING'
    WHEN v_dismissal_count = v_action_count THEN 'DISMISSED'
    ELSE 'MIXED_RESULT'
  END;
  v_event_final_status_label := CASE v_event_final_status_code WHEN 'FOR_FILING' THEN 'For Filing' WHEN 'DISMISSED' THEN 'Dismissed' ELSE 'Mixed Result' END;

  SELECT
    count(*) FILTER (WHERE decision_code = 'FOR_FILING'),
    count(*) FILTER (WHERE decision_code = 'DISMISSAL')
  INTO v_existing_for_filing_count, v_existing_dismissal_count
  FROM public.case_resolution_approval_actions aa
  JOIN public.case_resolution_approvals a ON a.id = aa.approval_id
  WHERE aa.case_id = p_case_id
    AND a.is_voided = false;

  v_total_for_filing_count := COALESCE(v_existing_for_filing_count, 0) + COALESCE(v_for_filing_count, 0);
  v_total_dismissal_count := COALESCE(v_existing_dismissal_count, 0) + COALESCE(v_dismissal_count, 0);
  v_total_action_count := v_total_for_filing_count + v_total_dismissal_count;

  IF v_total_action_count < 1 THEN
    RAISE EXCEPTION 'At least one approval action is required';
  ELSIF v_total_for_filing_count > 0 AND v_total_dismissal_count > 0 THEN
    v_case_final_status_code := 'MIXED_RESULT';
  ELSIF v_total_for_filing_count > 0 THEN
    v_case_final_status_code := 'FOR_FILING';
  ELSIF v_total_dismissal_count > 0 THEN
    v_case_final_status_code := 'DISMISSED';
  END IF;

  v_case_final_status_label := CASE v_case_final_status_code WHEN 'FOR_FILING' THEN 'For Filing' WHEN 'DISMISSED' THEN 'Dismissed' ELSE 'Mixed Result' END;

  INSERT INTO public.case_event_types (code, display_label, category, description, sort_order, is_system, is_active)
  VALUES ('CASE_DECISION_APPROVED', 'Case Decision Approved', 'CASE', 'Manual timeline event for approving a prosecutor recommendation or final case decision.', 130, true, true)
  ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, category = EXCLUDED.category, description = EXCLUDED.description, sort_order = EXCLUDED.sort_order, is_active = true, updated_at = now()
  RETURNING id INTO v_event_type_id;

  INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
  VALUES (v_case_final_status_code, v_case_final_status_label, CASE v_case_final_status_code WHEN 'FOR_FILING' THEN 90 WHEN 'DISMISSED' THEN 100 ELSE 110 END, true, true, true)
  ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, sort_order = EXCLUDED.sort_order, is_final = true, is_milestone = true, is_active = true
  RETURNING id INTO v_status_id;

  SELECT cpd.current_status_id, to_jsonb(cpd) INTO v_previous_status_id, v_old_details
  FROM public.case_private_details cpd WHERE cpd.case_id = p_case_id;

  INSERT INTO public.case_events (case_id, event_type_id, event_date, event_time, title, description, status_id, details_jsonb, source, created_by_user_id, updated_by_user_id)
  VALUES (p_case_id, v_event_type_id, p_date_approved, p_time_approved, 'Case Decision Approved', 'Decision approved by Prosec ' || v_approver_name || ' on ' || to_char(p_date_approved, 'Mon FMDD, YYYY'), v_status_id,
    jsonb_build_object('approved_by_prosecutor_id', p_approved_by_prosecutor_id, 'approved_by_name', v_approver_name, 'date_approved', p_date_approved, 'time_approved', p_time_approved, 'final_status_code', v_case_final_status_code, 'final_status_label', v_case_final_status_label, 'event_final_status_code', v_event_final_status_code, 'event_final_status_label', v_event_final_status_label, 'case_final_status_code', v_case_final_status_code, 'case_final_status_label', v_case_final_status_label, 'remarks', v_remarks),
    'MANUAL_ENTRY', p_user_id, p_user_id)
  RETURNING id INTO v_event_id;

  INSERT INTO public.case_resolution_approvals (case_id, case_event_id, case_resolution_id, approved_by_prosecutor_id, date_approved, time_approved, final_status_code, remarks, created_by_user_id, updated_by_user_id)
  VALUES (p_case_id, v_event_id, p_case_resolution_id, p_approved_by_prosecutor_id, p_date_approved, p_time_approved, v_event_final_status_code, v_remarks, p_user_id, p_user_id)
  RETURNING id INTO v_approval_id;

  FOR v_action IN SELECT * FROM jsonb_array_elements(COALESCE(p_approval_actions, '[]'::jsonb)) LOOP
    IF NULLIF(btrim(COALESCE(v_action->>'charge_text', '')), '') IS NOT NULL AND v_action->>'decision_code' IN ('FOR_FILING', 'DISMISSAL') THEN
      IF NULLIF(v_action->>'source_resolution_charge_action_id', '') IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM public.case_resolution_charge_actions src
        WHERE src.id = NULLIF(v_action->>'source_resolution_charge_action_id', '')::bigint
          AND src.case_id = p_case_id
          AND src.case_resolution_id = p_case_resolution_id
      ) THEN
        RAISE EXCEPTION 'Selected recommendation action does not belong to this case resolution.';
      END IF;

      v_display_order := v_display_order + 1;
      INSERT INTO public.case_resolution_approval_actions (approval_id, case_id, source_resolution_charge_action_id, case_violation_id, violation_id, charge_text, decision_code, display_order, remarks)
      VALUES (v_approval_id, p_case_id, NULLIF(v_action->>'source_resolution_charge_action_id', '')::bigint, NULLIF(v_action->>'case_violation_id', '')::bigint, NULLIF(v_action->>'violation_id', '')::bigint, NULLIF(btrim(v_action->>'charge_text'), ''), v_action->>'decision_code', v_display_order, NULLIF(btrim(COALESCE(v_action->>'remarks', '')), ''));
    END IF;
  END LOOP;

  UPDATE public.case_events
  SET source_table = 'case_resolution_approvals', source_id = v_approval_id,
      details_jsonb = details_jsonb || jsonb_build_object('approval_actions', COALESCE((SELECT jsonb_agg(jsonb_build_object('id', aa.id, 'source_resolution_charge_action_id', aa.source_resolution_charge_action_id, 'case_violation_id', aa.case_violation_id, 'violation_id', aa.violation_id, 'charge_text', aa.charge_text, 'decision_code', aa.decision_code, 'display_order', aa.display_order, 'remarks', aa.remarks) ORDER BY aa.display_order, aa.id) FROM public.case_resolution_approval_actions aa WHERE aa.approval_id = v_approval_id), '[]'::jsonb)),
      updated_by_user_id = p_user_id, updated_at = now()
  WHERE id = v_event_id;

  INSERT INTO public.case_private_details (case_id, current_status_id, current_status_date, current_status_remarks, updated_at)
  VALUES (p_case_id, v_status_id, p_date_approved, v_remarks, now())
  ON CONFLICT (case_id) DO UPDATE SET current_status_id = EXCLUDED.current_status_id, current_status_date = EXCLUDED.current_status_date, current_status_remarks = EXCLUDED.current_status_remarks, updated_at = now();

  INSERT INTO public.case_status_history (case_id, from_status_id, to_status_id, changed_by_user_id, changed_at, status_date, remarks, case_event_id)
  VALUES (p_case_id, v_previous_status_id, v_status_id, p_user_id, now(), p_date_approved, v_remarks, v_event_id)
  RETURNING id INTO v_status_history_id;

  SELECT to_jsonb(cpd) INTO v_new_details FROM public.case_private_details cpd WHERE cpd.case_id = p_case_id;

  INSERT INTO public.audit_logs (actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata)
  VALUES (p_user_id, 'case_resolution_approvals', v_approval_id, 'CASE_DECISION_APPROVED', v_old_details, v_new_details, p_case_id, 'Case decision approved as ' || v_case_final_status_label || '.', jsonb_build_object('case_event_id', v_event_id, 'status_history_id', v_status_history_id, 'event_final_status_code', v_event_final_status_code, 'case_final_status_code', v_case_final_status_code));

  RETURN v_event_id;
END;
$$;


GRANT EXECUTE ON FUNCTION public.record_case_decision_approved_event(
  bigint,
  bigint,
  bigint,
  date,
  time without time zone,
  jsonb,
  text,
  bigint
) TO authenticated;


CREATE OR REPLACE FUNCTION public.void_case_event(
  p_case_event_id bigint,
  p_void_reason text,
  p_voided_by_user_id bigint DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old jsonb;
  v_new jsonb;
  v_case_id bigint;
  v_event_type_code text;
  v_source_table text;
  v_source_id bigint;
  v_assignment_id bigint;
  v_assignment_old jsonb;
  v_assignment_new jsonb;
  v_approval_id bigint;
  v_approval_old jsonb;
  v_approval_new jsonb;
  v_resolution_id bigint;
  v_resolution_old jsonb;
  v_resolution_new jsonb;
  v_previous_status_id bigint;
  v_recomputed_status_id bigint;
  v_recomputed_status_code text;
  v_recomputed_status_label text;
  v_remaining_for_filing_count integer;
  v_remaining_dismissal_count integer;
  v_remaining_resolution_count integer;
  v_active_assignment_count integer;
  v_status_history_id bigint;
  v_old_details jsonb;
  v_new_details jsonb;
  v_recompute_remarks text;
BEGIN
  IF nullif(trim(p_void_reason), '') IS NULL THEN
    RAISE EXCEPTION 'Void reason is required';
  END IF;

  SELECT to_jsonb(ce), ce.case_id, cet.code, ce.source_table, ce.source_id
  INTO v_old, v_case_id, v_event_type_code, v_source_table, v_source_id
  FROM public.case_events ce
  LEFT JOIN public.case_event_types cet ON cet.id = ce.event_type_id
  WHERE ce.id = p_case_event_id
    AND ce.is_voided = false;

  IF v_old IS NULL THEN
    RAISE EXCEPTION 'Active case event % not found', p_case_event_id;
  END IF;

  IF lower(coalesce(v_source_table, '')) = 'case_resolutions' OR v_event_type_code = 'CASE_RESOLVED' THEN
    SELECT cr.id, to_jsonb(cr)
    INTO v_resolution_id, v_resolution_old
    FROM public.case_resolutions cr
    WHERE cr.id = v_source_id
       OR cr.case_event_id = p_case_event_id
    ORDER BY CASE WHEN cr.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_resolution_id IS NOT NULL AND EXISTS (
      SELECT 1
      FROM public.case_resolution_approvals a
      WHERE a.case_resolution_id = v_resolution_id
        AND a.is_voided = false
    ) THEN
      RAISE EXCEPTION 'This resolution already has approved decisions. Void the approval events first.';
    END IF;
  END IF;

  SELECT cpd.current_status_id, to_jsonb(cpd)
  INTO v_previous_status_id, v_old_details
  FROM public.case_private_details cpd
  WHERE cpd.case_id = v_case_id;

  UPDATE public.case_events
  SET is_voided = true,
      void_reason = p_void_reason,
      voided_at = now(),
      voided_by_user_id = p_voided_by_user_id,
      updated_by_user_id = p_voided_by_user_id,
      updated_at = now()
  WHERE id = p_case_event_id;

  SELECT to_jsonb(ce)
  INTO v_new
  FROM public.case_events ce
  WHERE ce.id = p_case_event_id;

  INSERT INTO public.audit_logs (
    actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata
  )
  VALUES (
    p_voided_by_user_id, 'case_events', p_case_event_id, 'VOID_CASE_EVENT', v_old, v_new, v_case_id,
    'Voided case timeline activity', jsonb_build_object('reason', p_void_reason)
  );

  IF lower(coalesce(v_source_table, '')) = 'case_assignments' OR v_event_type_code = 'CASE_ASSIGNMENT' THEN
    SELECT ca.id, to_jsonb(ca)
    INTO v_assignment_id, v_assignment_old
    FROM public.case_assignments ca
    WHERE ca.id = v_source_id
       OR ca.case_event_id = p_case_event_id
    ORDER BY CASE WHEN ca.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_assignment_id IS NOT NULL THEN
      UPDATE public.case_assignments
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          unassigned_at = COALESCE(unassigned_at, now())
      WHERE id = v_assignment_id;

      SELECT to_jsonb(ca)
      INTO v_assignment_new
      FROM public.case_assignments ca
      WHERE ca.id = v_assignment_id;

      INSERT INTO public.audit_logs (
        actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata
      )
      VALUES (
        p_voided_by_user_id,
        'case_assignments',
        v_assignment_id,
        'VOID_CASE_ASSIGNMENT_FROM_EVENT',
        v_assignment_old,
        v_assignment_new,
        v_case_id,
        'Assignment row voided because the Case Assignment event was voided.',
        jsonb_build_object('case_event_id', p_case_event_id, 'reason', p_void_reason)
      );
    END IF;
  END IF;

  IF lower(coalesce(v_source_table, '')) = 'case_resolutions' OR v_event_type_code = 'CASE_RESOLVED' THEN
    SELECT cr.id, to_jsonb(cr)
    INTO v_resolution_id, v_resolution_old
    FROM public.case_resolutions cr
    WHERE cr.id = v_source_id
       OR cr.case_event_id = p_case_event_id
    ORDER BY CASE WHEN cr.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_resolution_id IS NOT NULL THEN
      UPDATE public.case_resolutions
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      WHERE id = v_resolution_id;

      SELECT to_jsonb(cr)
      INTO v_resolution_new
      FROM public.case_resolutions cr
      WHERE cr.id = v_resolution_id;

      SELECT
        count(*) FILTER (WHERE aa.decision_code = 'FOR_FILING'),
        count(*) FILTER (WHERE aa.decision_code = 'DISMISSAL')
      INTO v_remaining_for_filing_count, v_remaining_dismissal_count
      FROM public.case_resolution_approval_actions aa
      JOIN public.case_resolution_approvals a ON a.id = aa.approval_id
      WHERE aa.case_id = v_case_id
        AND a.is_voided = false;

      IF COALESCE(v_remaining_for_filing_count, 0) > 0 AND COALESCE(v_remaining_dismissal_count, 0) > 0 THEN
        v_recomputed_status_code := 'MIXED_RESULT';
        v_recomputed_status_label := 'Mixed Result';
      ELSIF COALESCE(v_remaining_for_filing_count, 0) > 0 THEN
        v_recomputed_status_code := 'FOR_FILING';
        v_recomputed_status_label := 'For Filing';
      ELSIF COALESCE(v_remaining_dismissal_count, 0) > 0 THEN
        v_recomputed_status_code := 'DISMISSED';
        v_recomputed_status_label := 'Dismissed';
      ELSE
        SELECT count(*)
        INTO v_remaining_resolution_count
        FROM public.case_resolutions cr
        WHERE cr.case_id = v_case_id
          AND cr.is_voided = false;

        IF COALESCE(v_remaining_resolution_count, 0) > 0 THEN
          v_recomputed_status_code := 'RESO_FOR_APPROVAL';
          v_recomputed_status_label := 'Reso for Approval';
        ELSE
          SELECT count(*)
          INTO v_active_assignment_count
          FROM public.case_assignments ca
          WHERE ca.case_id = v_case_id
            AND ca.unassigned_at IS NULL
            AND ca.is_voided IS FALSE;

          IF COALESCE(v_active_assignment_count, 0) > 0 THEN
            v_recomputed_status_code := 'PENDING';
            v_recomputed_status_label := 'Pending';
          END IF;
        END IF;
      END IF;

      IF v_recomputed_status_code IS NOT NULL THEN
        v_recompute_remarks := 'Case resolution voided. Status recomputed from remaining approvals/resolutions.';

        INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
        VALUES (v_recomputed_status_code, v_recomputed_status_label, CASE v_recomputed_status_code WHEN 'PENDING' THEN 20 WHEN 'RESO_FOR_APPROVAL' THEN 80 WHEN 'FOR_FILING' THEN 90 WHEN 'DISMISSED' THEN 100 ELSE 110 END, v_recomputed_status_code NOT IN ('PENDING', 'RESO_FOR_APPROVAL'), v_recomputed_status_code <> 'PENDING', true)
        ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, sort_order = EXCLUDED.sort_order, is_final = EXCLUDED.is_final, is_milestone = EXCLUDED.is_milestone, is_active = true
        RETURNING id INTO v_recomputed_status_id;

        INSERT INTO public.case_private_details (case_id, current_status_id, current_status_date, current_status_remarks, updated_at)
        VALUES (v_case_id, v_recomputed_status_id, CURRENT_DATE, v_recompute_remarks, now())
        ON CONFLICT (case_id) DO UPDATE SET
          current_status_id = EXCLUDED.current_status_id,
          current_status_date = EXCLUDED.current_status_date,
          current_status_remarks = EXCLUDED.current_status_remarks,
          updated_at = now();

        INSERT INTO public.case_status_history (case_id, from_status_id, to_status_id, changed_by_user_id, changed_at, status_date, remarks, case_event_id)
        VALUES (v_case_id, v_previous_status_id, v_recomputed_status_id, p_voided_by_user_id, now(), CURRENT_DATE, v_recompute_remarks, p_case_event_id)
        RETURNING id INTO v_status_history_id;

        SELECT to_jsonb(cpd)
        INTO v_new_details
        FROM public.case_private_details cpd
        WHERE cpd.case_id = v_case_id;
      END IF;

      INSERT INTO public.audit_logs (
        actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata
      )
      VALUES (
        p_voided_by_user_id,
        'case_resolutions',
        v_resolution_id,
        'VOID_CASE_RESOLUTION_FROM_EVENT',
        COALESCE(v_resolution_old, v_old_details),
        jsonb_build_object('resolution', v_resolution_new, 'case_private_details', v_new_details),
        v_case_id,
        'Case resolution voided and case status recomputed.',
        jsonb_build_object('case_event_id', p_case_event_id, 'status_history_id', v_status_history_id, 'reason', p_void_reason, 'recomputed_status_code', v_recomputed_status_code)
      );
    END IF;
  END IF;

  IF lower(coalesce(v_source_table, '')) = 'case_resolution_approvals' OR v_event_type_code = 'CASE_DECISION_APPROVED' THEN
    SELECT a.id, to_jsonb(a)
    INTO v_approval_id, v_approval_old
    FROM public.case_resolution_approvals a
    WHERE a.id = v_source_id
       OR a.case_event_id = p_case_event_id
    ORDER BY CASE WHEN a.id = v_source_id THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_approval_id IS NOT NULL THEN
      UPDATE public.case_resolution_approvals
      SET is_voided = true,
          voided_at = now(),
          voided_by_user_id = p_voided_by_user_id,
          void_reason = p_void_reason,
          updated_by_user_id = p_voided_by_user_id,
          updated_at = now()
      WHERE id = v_approval_id;

      SELECT to_jsonb(a)
      INTO v_approval_new
      FROM public.case_resolution_approvals a
      WHERE a.id = v_approval_id;

      v_recompute_remarks := 'Case decision approval voided. Status recomputed from remaining approvals.';

      SELECT
        count(*) FILTER (WHERE aa.decision_code = 'FOR_FILING'),
        count(*) FILTER (WHERE aa.decision_code = 'DISMISSAL')
      INTO v_remaining_for_filing_count, v_remaining_dismissal_count
      FROM public.case_resolution_approval_actions aa
      JOIN public.case_resolution_approvals a ON a.id = aa.approval_id
      WHERE aa.case_id = v_case_id
        AND a.is_voided = false;

      IF COALESCE(v_remaining_for_filing_count, 0) > 0 AND COALESCE(v_remaining_dismissal_count, 0) > 0 THEN
        v_recomputed_status_code := 'MIXED_RESULT';
        v_recomputed_status_label := 'Mixed Result';
      ELSIF COALESCE(v_remaining_for_filing_count, 0) > 0 THEN
        v_recomputed_status_code := 'FOR_FILING';
        v_recomputed_status_label := 'For Filing';
      ELSIF COALESCE(v_remaining_dismissal_count, 0) > 0 THEN
        v_recomputed_status_code := 'DISMISSED';
        v_recomputed_status_label := 'Dismissed';
      ELSE
        v_recomputed_status_code := 'RESO_FOR_APPROVAL';
        v_recomputed_status_label := 'Reso for Approval';
      END IF;

      INSERT INTO public.case_statuses (code, display_label, sort_order, is_final, is_milestone, is_active)
      VALUES (v_recomputed_status_code, v_recomputed_status_label, CASE v_recomputed_status_code WHEN 'RESO_FOR_APPROVAL' THEN 80 WHEN 'FOR_FILING' THEN 90 WHEN 'DISMISSED' THEN 100 ELSE 110 END, v_recomputed_status_code <> 'RESO_FOR_APPROVAL', true, true)
      ON CONFLICT (code) DO UPDATE SET display_label = EXCLUDED.display_label, sort_order = EXCLUDED.sort_order, is_final = EXCLUDED.is_final, is_milestone = true, is_active = true
      RETURNING id INTO v_recomputed_status_id;

      INSERT INTO public.case_private_details (case_id, current_status_id, current_status_date, current_status_remarks, updated_at)
      VALUES (v_case_id, v_recomputed_status_id, CURRENT_DATE, v_recompute_remarks, now())
      ON CONFLICT (case_id) DO UPDATE SET
        current_status_id = EXCLUDED.current_status_id,
        current_status_date = EXCLUDED.current_status_date,
        current_status_remarks = EXCLUDED.current_status_remarks,
        updated_at = now();

      INSERT INTO public.case_status_history (case_id, from_status_id, to_status_id, changed_by_user_id, changed_at, status_date, remarks, case_event_id)
      VALUES (v_case_id, v_previous_status_id, v_recomputed_status_id, p_voided_by_user_id, now(), CURRENT_DATE, v_recompute_remarks, p_case_event_id)
      RETURNING id INTO v_status_history_id;

      SELECT to_jsonb(cpd)
      INTO v_new_details
      FROM public.case_private_details cpd
      WHERE cpd.case_id = v_case_id;

      INSERT INTO public.audit_logs (
        actor_user_id, entity_name, entity_id, action, old_data, new_data, case_id, summary, metadata
      )
      VALUES (
        p_voided_by_user_id,
        'case_resolution_approvals',
        v_approval_id,
        'VOID_CASE_DECISION_APPROVAL_FROM_EVENT',
        COALESCE(v_approval_old, v_old_details),
        jsonb_build_object('approval', v_approval_new, 'case_private_details', v_new_details),
        v_case_id,
        'Case decision approval was voided and case status was recomputed.',
        jsonb_build_object('case_event_id', p_case_event_id, 'status_history_id', v_status_history_id, 'reason', p_void_reason, 'recomputed_status_code', v_recomputed_status_code)
      );
    END IF;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.void_case_event(bigint, text, bigint) TO authenticated;
