name: OCP Backup Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      RCLONE_CONFIG_BASE64: ${{ secrets.RCLONE_CONFIG_BASE64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL 17
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release

          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

          pg_dump --version

      - name: Test database connection
        run: |
          psql "$DB_URL" \
          -c "select current_database(), current_user;"

      - name: Verify OCP tables
        run: |
          psql "$DB_URL" \
          -t \
          -c "select to_regclass('public.cases');"

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Restore rclone config
        run: |
          mkdir -p ~/.config/rclone

          printf "%s" "${RCLONE_CONFIG_BASE64}" \
          | base64 -d \
          > ~/.config/rclone/rclone.conf

      - name: Create test file
        run: |
          echo "GitHub Actions connected successfully." > test.txt

      - name: Upload test file
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")

          rclone mkdir "gdrive:OCP Gentri/Database Automatic backup/Auto Daily Backup/$TIMESTAMP"

          rclone copy test.txt \
          "gdrive:OCP Gentri/Database Automatic backup/Auto Daily Backup/$TIMESTAMP"

      - name: Done
        run: echo "Everything succeeded."
